/* valagtkmodule.c generated by valac, the Vala compiler
 * generated from valagtkmodule.vala, do not modify */

/* valagtkmodule.vala
 *
 * Copyright (C) 2013  Jürg Billeter
 * Copyright (C) 2013  Luca Bruno
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.

 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.

 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301  USA
 *
 * Author:
 * 	Luca Bruno <lucabru@src.gnome.org>
 */

#include <glib.h>
#include <glib-object.h>
#include <vala.h>
#include <valaccode.h>
#include <valagee.h>
#include <stdlib.h>
#include <string.h>
#include <glib/gstdio.h>


#define VALA_TYPE_CCODE_BASE_MODULE (vala_ccode_base_module_get_type ())
#define VALA_CCODE_BASE_MODULE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), VALA_TYPE_CCODE_BASE_MODULE, ValaCCodeBaseModule))
#define VALA_CCODE_BASE_MODULE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), VALA_TYPE_CCODE_BASE_MODULE, ValaCCodeBaseModuleClass))
#define VALA_IS_CCODE_BASE_MODULE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), VALA_TYPE_CCODE_BASE_MODULE))
#define VALA_IS_CCODE_BASE_MODULE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), VALA_TYPE_CCODE_BASE_MODULE))
#define VALA_CCODE_BASE_MODULE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), VALA_TYPE_CCODE_BASE_MODULE, ValaCCodeBaseModuleClass))

typedef struct _ValaCCodeBaseModule ValaCCodeBaseModule;
typedef struct _ValaCCodeBaseModuleClass ValaCCodeBaseModuleClass;
typedef struct _ValaCCodeBaseModulePrivate ValaCCodeBaseModulePrivate;

#define VALA_CCODE_BASE_MODULE_TYPE_EMIT_CONTEXT (vala_ccode_base_module_emit_context_get_type ())
#define VALA_CCODE_BASE_MODULE_EMIT_CONTEXT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), VALA_CCODE_BASE_MODULE_TYPE_EMIT_CONTEXT, ValaCCodeBaseModuleEmitContext))
#define VALA_CCODE_BASE_MODULE_EMIT_CONTEXT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), VALA_CCODE_BASE_MODULE_TYPE_EMIT_CONTEXT, ValaCCodeBaseModuleEmitContextClass))
#define VALA_CCODE_BASE_MODULE_IS_EMIT_CONTEXT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), VALA_CCODE_BASE_MODULE_TYPE_EMIT_CONTEXT))
#define VALA_CCODE_BASE_MODULE_IS_EMIT_CONTEXT_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), VALA_CCODE_BASE_MODULE_TYPE_EMIT_CONTEXT))
#define VALA_CCODE_BASE_MODULE_EMIT_CONTEXT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), VALA_CCODE_BASE_MODULE_TYPE_EMIT_CONTEXT, ValaCCodeBaseModuleEmitContextClass))

typedef struct _ValaCCodeBaseModuleEmitContext ValaCCodeBaseModuleEmitContext;
typedef struct _ValaCCodeBaseModuleEmitContextClass ValaCCodeBaseModuleEmitContextClass;

#define VALA_TYPE_CCODE_STRUCT_MODULE (vala_ccode_struct_module_get_type ())
#define VALA_CCODE_STRUCT_MODULE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), VALA_TYPE_CCODE_STRUCT_MODULE, ValaCCodeStructModule))
#define VALA_CCODE_STRUCT_MODULE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), VALA_TYPE_CCODE_STRUCT_MODULE, ValaCCodeStructModuleClass))
#define VALA_IS_CCODE_STRUCT_MODULE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), VALA_TYPE_CCODE_STRUCT_MODULE))
#define VALA_IS_CCODE_STRUCT_MODULE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), VALA_TYPE_CCODE_STRUCT_MODULE))
#define VALA_CCODE_STRUCT_MODULE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), VALA_TYPE_CCODE_STRUCT_MODULE, ValaCCodeStructModuleClass))

typedef struct _ValaCCodeStructModule ValaCCodeStructModule;
typedef struct _ValaCCodeStructModuleClass ValaCCodeStructModuleClass;
typedef struct _ValaCCodeStructModulePrivate ValaCCodeStructModulePrivate;

#define VALA_TYPE_CCODE_METHOD_MODULE (vala_ccode_method_module_get_type ())
#define VALA_CCODE_METHOD_MODULE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), VALA_TYPE_CCODE_METHOD_MODULE, ValaCCodeMethodModule))
#define VALA_CCODE_METHOD_MODULE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), VALA_TYPE_CCODE_METHOD_MODULE, ValaCCodeMethodModuleClass))
#define VALA_IS_CCODE_METHOD_MODULE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), VALA_TYPE_CCODE_METHOD_MODULE))
#define VALA_IS_CCODE_METHOD_MODULE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), VALA_TYPE_CCODE_METHOD_MODULE))
#define VALA_CCODE_METHOD_MODULE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), VALA_TYPE_CCODE_METHOD_MODULE, ValaCCodeMethodModuleClass))

typedef struct _ValaCCodeMethodModule ValaCCodeMethodModule;
typedef struct _ValaCCodeMethodModuleClass ValaCCodeMethodModuleClass;
typedef struct _ValaCCodeMethodModulePrivate ValaCCodeMethodModulePrivate;

#define VALA_TYPE_CCODE_CONTROL_FLOW_MODULE (vala_ccode_control_flow_module_get_type ())
#define VALA_CCODE_CONTROL_FLOW_MODULE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), VALA_TYPE_CCODE_CONTROL_FLOW_MODULE, ValaCCodeControlFlowModule))
#define VALA_CCODE_CONTROL_FLOW_MODULE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), VALA_TYPE_CCODE_CONTROL_FLOW_MODULE, ValaCCodeControlFlowModuleClass))
#define VALA_IS_CCODE_CONTROL_FLOW_MODULE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), VALA_TYPE_CCODE_CONTROL_FLOW_MODULE))
#define VALA_IS_CCODE_CONTROL_FLOW_MODULE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), VALA_TYPE_CCODE_CONTROL_FLOW_MODULE))
#define VALA_CCODE_CONTROL_FLOW_MODULE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), VALA_TYPE_CCODE_CONTROL_FLOW_MODULE, ValaCCodeControlFlowModuleClass))

typedef struct _ValaCCodeControlFlowModule ValaCCodeControlFlowModule;
typedef struct _ValaCCodeControlFlowModuleClass ValaCCodeControlFlowModuleClass;
typedef struct _ValaCCodeControlFlowModulePrivate ValaCCodeControlFlowModulePrivate;

#define VALA_TYPE_CCODE_MEMBER_ACCESS_MODULE (vala_ccode_member_access_module_get_type ())
#define VALA_CCODE_MEMBER_ACCESS_MODULE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), VALA_TYPE_CCODE_MEMBER_ACCESS_MODULE, ValaCCodeMemberAccessModule))
#define VALA_CCODE_MEMBER_ACCESS_MODULE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), VALA_TYPE_CCODE_MEMBER_ACCESS_MODULE, ValaCCodeMemberAccessModuleClass))
#define VALA_IS_CCODE_MEMBER_ACCESS_MODULE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), VALA_TYPE_CCODE_MEMBER_ACCESS_MODULE))
#define VALA_IS_CCODE_MEMBER_ACCESS_MODULE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), VALA_TYPE_CCODE_MEMBER_ACCESS_MODULE))
#define VALA_CCODE_MEMBER_ACCESS_MODULE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), VALA_TYPE_CCODE_MEMBER_ACCESS_MODULE, ValaCCodeMemberAccessModuleClass))

typedef struct _ValaCCodeMemberAccessModule ValaCCodeMemberAccessModule;
typedef struct _ValaCCodeMemberAccessModuleClass ValaCCodeMemberAccessModuleClass;
typedef struct _ValaCCodeMemberAccessModulePrivate ValaCCodeMemberAccessModulePrivate;

#define VALA_TYPE_CCODE_ASSIGNMENT_MODULE (vala_ccode_assignment_module_get_type ())
#define VALA_CCODE_ASSIGNMENT_MODULE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), VALA_TYPE_CCODE_ASSIGNMENT_MODULE, ValaCCodeAssignmentModule))
#define VALA_CCODE_ASSIGNMENT_MODULE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), VALA_TYPE_CCODE_ASSIGNMENT_MODULE, ValaCCodeAssignmentModuleClass))
#define VALA_IS_CCODE_ASSIGNMENT_MODULE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), VALA_TYPE_CCODE_ASSIGNMENT_MODULE))
#define VALA_IS_CCODE_ASSIGNMENT_MODULE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), VALA_TYPE_CCODE_ASSIGNMENT_MODULE))
#define VALA_CCODE_ASSIGNMENT_MODULE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), VALA_TYPE_CCODE_ASSIGNMENT_MODULE, ValaCCodeAssignmentModuleClass))

typedef struct _ValaCCodeAssignmentModule ValaCCodeAssignmentModule;
typedef struct _ValaCCodeAssignmentModuleClass ValaCCodeAssignmentModuleClass;
typedef struct _ValaCCodeAssignmentModulePrivate ValaCCodeAssignmentModulePrivate;

#define VALA_TYPE_CCODE_METHOD_CALL_MODULE (vala_ccode_method_call_module_get_type ())
#define VALA_CCODE_METHOD_CALL_MODULE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), VALA_TYPE_CCODE_METHOD_CALL_MODULE, ValaCCodeMethodCallModule))
#define VALA_CCODE_METHOD_CALL_MODULE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), VALA_TYPE_CCODE_METHOD_CALL_MODULE, ValaCCodeMethodCallModuleClass))
#define VALA_IS_CCODE_METHOD_CALL_MODULE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), VALA_TYPE_CCODE_METHOD_CALL_MODULE))
#define VALA_IS_CCODE_METHOD_CALL_MODULE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), VALA_TYPE_CCODE_METHOD_CALL_MODULE))
#define VALA_CCODE_METHOD_CALL_MODULE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), VALA_TYPE_CCODE_METHOD_CALL_MODULE, ValaCCodeMethodCallModuleClass))

typedef struct _ValaCCodeMethodCallModule ValaCCodeMethodCallModule;
typedef struct _ValaCCodeMethodCallModuleClass ValaCCodeMethodCallModuleClass;
typedef struct _ValaCCodeMethodCallModulePrivate ValaCCodeMethodCallModulePrivate;

#define VALA_TYPE_CCODE_ARRAY_MODULE (vala_ccode_array_module_get_type ())
#define VALA_CCODE_ARRAY_MODULE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), VALA_TYPE_CCODE_ARRAY_MODULE, ValaCCodeArrayModule))
#define VALA_CCODE_ARRAY_MODULE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), VALA_TYPE_CCODE_ARRAY_MODULE, ValaCCodeArrayModuleClass))
#define VALA_IS_CCODE_ARRAY_MODULE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), VALA_TYPE_CCODE_ARRAY_MODULE))
#define VALA_IS_CCODE_ARRAY_MODULE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), VALA_TYPE_CCODE_ARRAY_MODULE))
#define VALA_CCODE_ARRAY_MODULE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), VALA_TYPE_CCODE_ARRAY_MODULE, ValaCCodeArrayModuleClass))

typedef struct _ValaCCodeArrayModule ValaCCodeArrayModule;
typedef struct _ValaCCodeArrayModuleClass ValaCCodeArrayModuleClass;
typedef struct _ValaCCodeArrayModulePrivate ValaCCodeArrayModulePrivate;

#define VALA_TYPE_CCODE_DELEGATE_MODULE (vala_ccode_delegate_module_get_type ())
#define VALA_CCODE_DELEGATE_MODULE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), VALA_TYPE_CCODE_DELEGATE_MODULE, ValaCCodeDelegateModule))
#define VALA_CCODE_DELEGATE_MODULE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), VALA_TYPE_CCODE_DELEGATE_MODULE, ValaCCodeDelegateModuleClass))
#define VALA_IS_CCODE_DELEGATE_MODULE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), VALA_TYPE_CCODE_DELEGATE_MODULE))
#define VALA_IS_CCODE_DELEGATE_MODULE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), VALA_TYPE_CCODE_DELEGATE_MODULE))
#define VALA_CCODE_DELEGATE_MODULE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), VALA_TYPE_CCODE_DELEGATE_MODULE, ValaCCodeDelegateModuleClass))

typedef struct _ValaCCodeDelegateModule ValaCCodeDelegateModule;
typedef struct _ValaCCodeDelegateModuleClass ValaCCodeDelegateModuleClass;
typedef struct _ValaCCodeDelegateModulePrivate ValaCCodeDelegateModulePrivate;

#define VALA_TYPE_GERROR_MODULE (vala_gerror_module_get_type ())
#define VALA_GERROR_MODULE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), VALA_TYPE_GERROR_MODULE, ValaGErrorModule))
#define VALA_GERROR_MODULE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), VALA_TYPE_GERROR_MODULE, ValaGErrorModuleClass))
#define VALA_IS_GERROR_MODULE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), VALA_TYPE_GERROR_MODULE))
#define VALA_IS_GERROR_MODULE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), VALA_TYPE_GERROR_MODULE))
#define VALA_GERROR_MODULE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), VALA_TYPE_GERROR_MODULE, ValaGErrorModuleClass))

typedef struct _ValaGErrorModule ValaGErrorModule;
typedef struct _ValaGErrorModuleClass ValaGErrorModuleClass;
typedef struct _ValaGErrorModulePrivate ValaGErrorModulePrivate;

#define VALA_TYPE_GTYPE_MODULE (vala_gtype_module_get_type ())
#define VALA_GTYPE_MODULE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), VALA_TYPE_GTYPE_MODULE, ValaGTypeModule))
#define VALA_GTYPE_MODULE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), VALA_TYPE_GTYPE_MODULE, ValaGTypeModuleClass))
#define VALA_IS_GTYPE_MODULE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), VALA_TYPE_GTYPE_MODULE))
#define VALA_IS_GTYPE_MODULE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), VALA_TYPE_GTYPE_MODULE))
#define VALA_GTYPE_MODULE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), VALA_TYPE_GTYPE_MODULE, ValaGTypeModuleClass))

typedef struct _ValaGTypeModule ValaGTypeModule;
typedef struct _ValaGTypeModuleClass ValaGTypeModuleClass;
typedef struct _ValaGTypeModulePrivate ValaGTypeModulePrivate;

#define VALA_TYPE_GOBJECT_MODULE (vala_gobject_module_get_type ())
#define VALA_GOBJECT_MODULE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), VALA_TYPE_GOBJECT_MODULE, ValaGObjectModule))
#define VALA_GOBJECT_MODULE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), VALA_TYPE_GOBJECT_MODULE, ValaGObjectModuleClass))
#define VALA_IS_GOBJECT_MODULE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), VALA_TYPE_GOBJECT_MODULE))
#define VALA_IS_GOBJECT_MODULE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), VALA_TYPE_GOBJECT_MODULE))
#define VALA_GOBJECT_MODULE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), VALA_TYPE_GOBJECT_MODULE, ValaGObjectModuleClass))

typedef struct _ValaGObjectModule ValaGObjectModule;
typedef struct _ValaGObjectModuleClass ValaGObjectModuleClass;
typedef struct _ValaGObjectModulePrivate ValaGObjectModulePrivate;

#define VALA_TYPE_GSIGNAL_MODULE (vala_gsignal_module_get_type ())
#define VALA_GSIGNAL_MODULE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), VALA_TYPE_GSIGNAL_MODULE, ValaGSignalModule))
#define VALA_GSIGNAL_MODULE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), VALA_TYPE_GSIGNAL_MODULE, ValaGSignalModuleClass))
#define VALA_IS_GSIGNAL_MODULE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), VALA_TYPE_GSIGNAL_MODULE))
#define VALA_IS_GSIGNAL_MODULE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), VALA_TYPE_GSIGNAL_MODULE))
#define VALA_GSIGNAL_MODULE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), VALA_TYPE_GSIGNAL_MODULE, ValaGSignalModuleClass))

typedef struct _ValaGSignalModule ValaGSignalModule;
typedef struct _ValaGSignalModuleClass ValaGSignalModuleClass;
typedef struct _ValaGSignalModulePrivate ValaGSignalModulePrivate;

#define VALA_TYPE_GTK_MODULE (vala_gtk_module_get_type ())
#define VALA_GTK_MODULE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), VALA_TYPE_GTK_MODULE, ValaGtkModule))
#define VALA_GTK_MODULE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), VALA_TYPE_GTK_MODULE, ValaGtkModuleClass))
#define VALA_IS_GTK_MODULE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), VALA_TYPE_GTK_MODULE))
#define VALA_IS_GTK_MODULE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), VALA_TYPE_GTK_MODULE))
#define VALA_GTK_MODULE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), VALA_TYPE_GTK_MODULE, ValaGtkModuleClass))

typedef struct _ValaGtkModule ValaGtkModule;
typedef struct _ValaGtkModuleClass ValaGtkModuleClass;
typedef struct _ValaGtkModulePrivate ValaGtkModulePrivate;
#define _vala_map_unref0(var) ((var == NULL) ? NULL : (var = (vala_map_unref (var), NULL)))
#define _g_free0(var) (var = (g_free (var), NULL))
#define _vala_code_node_unref0(var) ((var == NULL) ? NULL : (var = (vala_code_node_unref (var), NULL)))
#define _vala_iterable_unref0(var) ((var == NULL) ? NULL : (var = (vala_iterable_unref (var), NULL)))
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _g_regex_unref0(var) ((var == NULL) ? NULL : (var = (g_regex_unref (var), NULL)))
#define _g_error_free0(var) ((var == NULL) ? NULL : (var = (g_error_free (var), NULL)))
#define _vala_ccode_node_unref0(var) ((var == NULL) ? NULL : (var = (vala_ccode_node_unref (var), NULL)))

struct _ValaCCodeBaseModule {
	ValaCodeGenerator parent_instance;
	ValaCCodeBaseModulePrivate * priv;
	ValaSymbol* root_symbol;
	ValaCCodeBaseModuleEmitContext* emit_context;
	ValaCCodeLineDirective* current_line;
	ValaCCodeFile* header_file;
	ValaCCodeFile* internal_header_file;
	ValaCCodeFile* cfile;
	ValaCCodeBaseModuleEmitContext* class_init_context;
	ValaCCodeBaseModuleEmitContext* base_init_context;
	ValaCCodeBaseModuleEmitContext* class_finalize_context;
	ValaCCodeBaseModuleEmitContext* base_finalize_context;
	ValaCCodeBaseModuleEmitContext* instance_init_context;
	ValaCCodeBaseModuleEmitContext* instance_finalize_context;
	ValaCCodeStruct* param_spec_struct;
	ValaCCodeStruct* closure_struct;
	ValaCCodeEnum* prop_enum;
	ValaSet* user_marshal_set;
	ValaSet* predefined_marshal_set;
	gint next_regex_id;
	gint next_coroutine_state;
	ValaDataType* void_type;
	ValaDataType* bool_type;
	ValaDataType* char_type;
	ValaDataType* uchar_type;
	ValaDataType* unichar_type;
	ValaDataType* short_type;
	ValaDataType* ushort_type;
	ValaDataType* int_type;
	ValaDataType* uint_type;
	ValaDataType* long_type;
	ValaDataType* ulong_type;
	ValaDataType* int8_type;
	ValaDataType* uint8_type;
	ValaDataType* int16_type;
	ValaDataType* uint16_type;
	ValaDataType* int32_type;
	ValaDataType* uint32_type;
	ValaDataType* int64_type;
	ValaDataType* uint64_type;
	ValaDataType* string_type;
	ValaDataType* regex_type;
	ValaDataType* float_type;
	ValaDataType* double_type;
	ValaTypeSymbol* gtype_type;
	ValaTypeSymbol* gobject_type;
	ValaErrorType* gerror_type;
	ValaClass* glist_type;
	ValaClass* gslist_type;
	ValaClass* gnode_type;
	ValaClass* gqueue_type;
	ValaClass* gvaluearray_type;
	ValaTypeSymbol* gstringbuilder_type;
	ValaTypeSymbol* garray_type;
	ValaTypeSymbol* gbytearray_type;
	ValaTypeSymbol* gptrarray_type;
	ValaTypeSymbol* gthreadpool_type;
	ValaDataType* gdestroynotify_type;
	ValaDataType* gquark_type;
	ValaStruct* gvalue_type;
	ValaClass* gvariant_type;
	ValaStruct* mutex_type;
	ValaStruct* gmutex_type;
	ValaStruct* grecmutex_type;
	ValaStruct* grwlock_type;
	ValaStruct* gcond_type;
	ValaClass* gsource_type;
	ValaTypeSymbol* type_module_type;
	ValaTypeSymbol* dbus_proxy_type;
	ValaClass* gtk_widget_type;
	gboolean in_plugin;
	gchar* module_init_param_name;
	gboolean gvaluecollector_h_needed;
	gboolean requires_assert;
	gboolean requires_array_free;
	gboolean requires_array_move;
	gboolean requires_array_length;
	gboolean requires_clear_mutex;
	ValaSet* wrappers;
};

struct _ValaCCodeBaseModuleClass {
	ValaCodeGeneratorClass parent_class;
	void (*append_vala_array_free) (ValaCCodeBaseModule* self);
	void (*append_vala_array_move) (ValaCCodeBaseModule* self);
	void (*append_vala_array_length) (ValaCCodeBaseModule* self);
	gboolean (*generate_enum_declaration) (ValaCCodeBaseModule* self, ValaEnum* en, ValaCCodeFile* decl_space);
	void (*generate_class_struct_declaration) (ValaCCodeBaseModule* self, ValaClass* cl, ValaCCodeFile* decl_space);
	void (*generate_struct_declaration) (ValaCCodeBaseModule* self, ValaStruct* st, ValaCCodeFile* decl_space);
	void (*generate_delegate_declaration) (ValaCCodeBaseModule* self, ValaDelegate* d, ValaCCodeFile* decl_space);
	void (*generate_cparameters) (ValaCCodeBaseModule* self, ValaMethod* m, ValaCCodeFile* decl_space, ValaMap* cparam_map, ValaCCodeFunction* func, ValaCCodeFunctionDeclarator* vdeclarator, ValaMap* carg_map, ValaCCodeFunctionCall* vcall, gint direction);
	ValaCCodeExpression* (*get_dup_func_expression) (ValaCCodeBaseModule* self, ValaDataType* type, ValaSourceReference* source_reference, gboolean is_chainup);
	gchar* (*append_struct_array_free) (ValaCCodeBaseModule* self, ValaStruct* st);
	ValaCCodeExpression* (*destroy_value) (ValaCCodeBaseModule* self, ValaTargetValue* value, gboolean is_macro_definition);
	void (*append_scope_free) (ValaCCodeBaseModule* self, ValaSymbol* sym, ValaCodeNode* stop_at);
	ValaTargetValue* (*get_local_cvalue) (ValaCCodeBaseModule* self, ValaLocalVariable* local);
	ValaTargetValue* (*get_parameter_cvalue) (ValaCCodeBaseModule* self, ValaParameter* param);
	ValaTargetValue* (*get_field_cvalue) (ValaCCodeBaseModule* self, ValaField* field, ValaTargetValue* instance);
	ValaTargetValue* (*load_variable) (ValaCCodeBaseModule* self, ValaVariable* variable, ValaTargetValue* value);
	ValaTargetValue* (*load_this_parameter) (ValaCCodeBaseModule* self, ValaTypeSymbol* sym);
	void (*store_value) (ValaCCodeBaseModule* self, ValaTargetValue* lvalue, ValaTargetValue* value);
	gchar* (*get_delegate_target_cname) (ValaCCodeBaseModule* self, const gchar* delegate_cname);
	ValaCCodeExpression* (*get_delegate_target_cexpression) (ValaCCodeBaseModule* self, ValaExpression* delegate_expr, ValaCCodeExpression** delegate_target_destroy_notify);
	ValaCCodeExpression* (*get_delegate_target_cvalue) (ValaCCodeBaseModule* self, ValaTargetValue* value);
	ValaCCodeExpression* (*get_delegate_target_destroy_notify_cvalue) (ValaCCodeBaseModule* self, ValaTargetValue* value);
	gchar* (*get_delegate_target_destroy_notify_cname) (ValaCCodeBaseModule* self, const gchar* delegate_cname);
	ValaTargetValue* (*copy_value) (ValaCCodeBaseModule* self, ValaTargetValue* value, ValaCodeNode* node);
	void (*generate_class_declaration) (ValaCCodeBaseModule* self, ValaClass* cl, ValaCCodeFile* decl_space);
	void (*generate_interface_declaration) (ValaCCodeBaseModule* self, ValaInterface* iface, ValaCCodeFile* decl_space);
	void (*generate_method_declaration) (ValaCCodeBaseModule* self, ValaMethod* m, ValaCCodeFile* decl_space);
	void (*generate_error_domain_declaration) (ValaCCodeBaseModule* self, ValaErrorDomain* edomain, ValaCCodeFile* decl_space);
	ValaCCodeExpression* (*deserialize_expression) (ValaCCodeBaseModule* self, ValaDataType* type, ValaCCodeExpression* variant_expr, ValaCCodeExpression* expr, ValaCCodeExpression* error_expr, gboolean* may_fail);
	ValaCCodeExpression* (*serialize_expression) (ValaCCodeBaseModule* self, ValaDataType* type, ValaCCodeExpression* expr);
	ValaCCodeExpression* (*get_implicit_cast_expression) (ValaCCodeBaseModule* self, ValaCCodeExpression* source_cexpr, ValaDataType* expression_type, ValaDataType* target_type, ValaCodeNode* node);
	void (*create_type_check_statement) (ValaCCodeBaseModule* self, ValaCodeNode* method_node, ValaDataType* ret_type, ValaTypeSymbol* t, gboolean non_null, const gchar* var_name);
	gboolean (*is_gobject_property) (ValaCCodeBaseModule* self, ValaProperty* prop);
	void (*generate_dynamic_method_wrapper) (ValaCCodeBaseModule* self, ValaDynamicMethod* method);
	gboolean (*method_has_wrapper) (ValaCCodeBaseModule* self, ValaMethod* method);
	ValaCCodeFunctionCall* (*get_param_spec) (ValaCCodeBaseModule* self, ValaProperty* prop);
	ValaCCodeFunctionCall* (*get_signal_creation) (ValaCCodeBaseModule* self, ValaSignal* sig, ValaTypeSymbol* type);
	void (*register_dbus_info) (ValaCCodeBaseModule* self, ValaCCodeBlock* block, ValaObjectTypeSymbol* bindable);
	gchar* (*get_dynamic_property_getter_cname) (ValaCCodeBaseModule* self, ValaDynamicProperty* node);
	gchar* (*get_dynamic_property_setter_cname) (ValaCCodeBaseModule* self, ValaDynamicProperty* node);
	gchar* (*get_dynamic_signal_cname) (ValaCCodeBaseModule* self, ValaDynamicSignal* node);
	gchar* (*get_dynamic_signal_connect_wrapper_name) (ValaCCodeBaseModule* self, ValaDynamicSignal* node);
	gchar* (*get_dynamic_signal_connect_after_wrapper_name) (ValaCCodeBaseModule* self, ValaDynamicSignal* node);
	gchar* (*get_dynamic_signal_disconnect_wrapper_name) (ValaCCodeBaseModule* self, ValaDynamicSignal* node);
	gchar* (*get_array_length_cname) (ValaCCodeBaseModule* self, const gchar* array_cname, gint dim);
	gchar* (*get_parameter_array_length_cname) (ValaCCodeBaseModule* self, ValaParameter* param, gint dim);
	ValaCCodeExpression* (*get_array_length_cexpression) (ValaCCodeBaseModule* self, ValaExpression* array_expr, gint dim);
	ValaCCodeExpression* (*get_array_length_cvalue) (ValaCCodeBaseModule* self, ValaTargetValue* value, gint dim);
	gchar* (*get_array_size_cname) (ValaCCodeBaseModule* self, const gchar* array_cname);
	void (*add_simple_check) (ValaCCodeBaseModule* self, ValaCodeNode* node, gboolean always_fails);
	gchar* (*generate_ready_function) (ValaCCodeBaseModule* self, ValaMethod* m);
};

struct _ValaCCodeStructModule {
	ValaCCodeBaseModule parent_instance;
	ValaCCodeStructModulePrivate * priv;
};

struct _ValaCCodeStructModuleClass {
	ValaCCodeBaseModuleClass parent_class;
};

struct _ValaCCodeMethodModule {
	ValaCCodeStructModule parent_instance;
	ValaCCodeMethodModulePrivate * priv;
};

struct _ValaCCodeMethodModuleClass {
	ValaCCodeStructModuleClass parent_class;
	void (*generate_method_result_declaration) (ValaCCodeMethodModule* self, ValaMethod* m, ValaCCodeFile* decl_space, ValaCCodeFunction* cfunc, ValaMap* cparam_map, ValaMap* carg_map);
	ValaCCodeParameter* (*generate_parameter) (ValaCCodeMethodModule* self, ValaParameter* param, ValaCCodeFile* decl_space, ValaMap* cparam_map, ValaMap* carg_map);
};

struct _ValaCCodeControlFlowModule {
	ValaCCodeMethodModule parent_instance;
	ValaCCodeControlFlowModulePrivate * priv;
};

struct _ValaCCodeControlFlowModuleClass {
	ValaCCodeMethodModuleClass parent_class;
};

struct _ValaCCodeMemberAccessModule {
	ValaCCodeControlFlowModule parent_instance;
	ValaCCodeMemberAccessModulePrivate * priv;
};

struct _ValaCCodeMemberAccessModuleClass {
	ValaCCodeControlFlowModuleClass parent_class;
};

struct _ValaCCodeAssignmentModule {
	ValaCCodeMemberAccessModule parent_instance;
	ValaCCodeAssignmentModulePrivate * priv;
};

struct _ValaCCodeAssignmentModuleClass {
	ValaCCodeMemberAccessModuleClass parent_class;
};

struct _ValaCCodeMethodCallModule {
	ValaCCodeAssignmentModule parent_instance;
	ValaCCodeMethodCallModulePrivate * priv;
};

struct _ValaCCodeMethodCallModuleClass {
	ValaCCodeAssignmentModuleClass parent_class;
};

struct _ValaCCodeArrayModule {
	ValaCCodeMethodCallModule parent_instance;
	ValaCCodeArrayModulePrivate * priv;
};

struct _ValaCCodeArrayModuleClass {
	ValaCCodeMethodCallModuleClass parent_class;
};

struct _ValaCCodeDelegateModule {
	ValaCCodeArrayModule parent_instance;
	ValaCCodeDelegateModulePrivate * priv;
};

struct _ValaCCodeDelegateModuleClass {
	ValaCCodeArrayModuleClass parent_class;
};

struct _ValaGErrorModule {
	ValaCCodeDelegateModule parent_instance;
	ValaGErrorModulePrivate * priv;
};

struct _ValaGErrorModuleClass {
	ValaCCodeDelegateModuleClass parent_class;
	void (*return_with_exception) (ValaGErrorModule* self, ValaCCodeExpression* error_expr);
};

struct _ValaGTypeModule {
	ValaGErrorModule parent_instance;
	ValaGTypeModulePrivate * priv;
};

struct _ValaGTypeModuleClass {
	ValaGErrorModuleClass parent_class;
	void (*generate_virtual_method_declaration) (ValaGTypeModule* self, ValaMethod* m, ValaCCodeFile* decl_space, ValaCCodeStruct* type_struct);
	void (*generate_class_init) (ValaGTypeModule* self, ValaClass* cl);
	void (*generate_instance_init) (ValaGTypeModule* self, ValaClass* cl);
};

struct _ValaGObjectModule {
	ValaGTypeModule parent_instance;
	ValaGObjectModulePrivate * priv;
};

struct _ValaGObjectModuleClass {
	ValaGTypeModuleClass parent_class;
};

struct _ValaGSignalModule {
	ValaGObjectModule parent_instance;
	ValaGSignalModulePrivate * priv;
};

struct _ValaGSignalModuleClass {
	ValaGObjectModuleClass parent_class;
};

struct _ValaGtkModule {
	ValaGSignalModule parent_instance;
	ValaGtkModulePrivate * priv;
};

struct _ValaGtkModuleClass {
	ValaGSignalModuleClass parent_class;
};

struct _ValaGtkModulePrivate {
	ValaHashMap* cclass_to_vala_map;
	ValaHashMap* gresource_to_file_map;
	ValaHashMap* current_handler_to_signal_map;
	ValaHashMap* current_child_to_class_map;
};


static gpointer vala_gtk_module_parent_class = NULL;

GType vala_ccode_base_module_get_type (void) G_GNUC_CONST;
gpointer vala_ccode_base_module_emit_context_ref (gpointer instance);
void vala_ccode_base_module_emit_context_unref (gpointer instance);
GParamSpec* vala_ccode_base_module_param_spec_emit_context (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void vala_ccode_base_module_value_set_emit_context (GValue* value, gpointer v_object);
void vala_ccode_base_module_value_take_emit_context (GValue* value, gpointer v_object);
gpointer vala_ccode_base_module_value_get_emit_context (const GValue* value);
GType vala_ccode_base_module_emit_context_get_type (void) G_GNUC_CONST;
GType vala_ccode_struct_module_get_type (void) G_GNUC_CONST;
GType vala_ccode_method_module_get_type (void) G_GNUC_CONST;
GType vala_ccode_control_flow_module_get_type (void) G_GNUC_CONST;
GType vala_ccode_member_access_module_get_type (void) G_GNUC_CONST;
GType vala_ccode_assignment_module_get_type (void) G_GNUC_CONST;
GType vala_ccode_method_call_module_get_type (void) G_GNUC_CONST;
GType vala_ccode_array_module_get_type (void) G_GNUC_CONST;
GType vala_ccode_delegate_module_get_type (void) G_GNUC_CONST;
GType vala_gerror_module_get_type (void) G_GNUC_CONST;
GType vala_gtype_module_get_type (void) G_GNUC_CONST;
GType vala_gobject_module_get_type (void) G_GNUC_CONST;
GType vala_gsignal_module_get_type (void) G_GNUC_CONST;
GType vala_gtk_module_get_type (void) G_GNUC_CONST;
#define VALA_GTK_MODULE_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), VALA_TYPE_GTK_MODULE, ValaGtkModulePrivate))
enum  {
	VALA_GTK_MODULE_DUMMY_PROPERTY
};
static void vala_gtk_module_ensure_cclass_to_vala_map (ValaGtkModule* self);
static void vala_gtk_module_recurse_cclass_to_vala_map (ValaGtkModule* self, ValaNamespace* ns);
ValaCodeContext* vala_ccode_base_module_get_context (ValaCCodeBaseModule* self);
gchar* vala_ccode_base_module_get_ccode_name (ValaCodeNode* node);
static void vala_gtk_module_ensure_gresource_to_file_map (ValaGtkModule* self);
static void vala_gtk_module_process_current_ui_resource (ValaGtkModule* self, const gchar* ui_resource, ValaCodeNode* node);
static gboolean vala_gtk_module_is_gtk_template (ValaGtkModule* self, ValaClass* cl);
static void vala_gtk_module_real_generate_class_init (ValaGTypeModule* base, ValaClass* cl);
void vala_gtype_module_generate_class_init (ValaGTypeModule* self, ValaClass* cl);
ValaCCodeFunction* vala_ccode_base_module_get_ccode (ValaCCodeBaseModule* self);
static void vala_gtk_module_real_visit_field (ValaCodeVisitor* base, ValaField* f);
ValaClass* vala_ccode_base_module_get_current_class (ValaCCodeBaseModule* self);
void vala_ccode_base_module_push_context (ValaCCodeBaseModule* self, ValaCCodeBaseModuleEmitContext* emit_context);
void vala_ccode_base_module_pop_context (ValaCCodeBaseModule* self);
static void vala_gtk_module_real_visit_method (ValaCodeVisitor* base, ValaMethod* m);
gchar* vala_ccode_delegate_module_generate_delegate_wrapper (ValaCCodeDelegateModule* self, ValaMethod* m, ValaDelegateType* dt, ValaCodeNode* node);
static void vala_gtk_module_real_generate_instance_init (ValaGTypeModule* base, ValaClass* cl);
ValaGtkModule* vala_gtk_module_new (void);
ValaGtkModule* vala_gtk_module_construct (GType object_type);
ValaGSignalModule* vala_gsignal_module_new (void);
ValaGSignalModule* vala_gsignal_module_construct (GType object_type);
static void vala_gtk_module_finalize (ValaCodeVisitor* obj);


static void vala_gtk_module_ensure_cclass_to_vala_map (ValaGtkModule* self) {
	ValaHashMap* _tmp0_;
	GHashFunc _tmp1_;
	GEqualFunc _tmp2_;
	GEqualFunc _tmp3_;
	ValaHashMap* _tmp4_;
	ValaCodeContext* _tmp5_;
	ValaCodeContext* _tmp6_;
	ValaNamespace* _tmp7_;
	ValaNamespace* _tmp8_;
	g_return_if_fail (self != NULL);
	_tmp0_ = self->priv->cclass_to_vala_map;
	if (_tmp0_ != NULL) {
		return;
	}
	_tmp1_ = g_str_hash;
	_tmp2_ = g_str_equal;
	_tmp3_ = g_direct_equal;
	_tmp4_ = vala_hash_map_new (G_TYPE_STRING, (GBoxedCopyFunc) g_strdup, g_free, VALA_TYPE_CLASS, (GBoxedCopyFunc) vala_code_node_ref, vala_code_node_unref, _tmp1_, _tmp2_, _tmp3_);
	_vala_map_unref0 (self->priv->cclass_to_vala_map);
	self->priv->cclass_to_vala_map = _tmp4_;
	_tmp5_ = vala_ccode_base_module_get_context ((ValaCCodeBaseModule*) self);
	_tmp6_ = _tmp5_;
	_tmp7_ = vala_code_context_get_root (_tmp6_);
	_tmp8_ = _tmp7_;
	vala_gtk_module_recurse_cclass_to_vala_map (self, _tmp8_);
}


static void vala_gtk_module_recurse_cclass_to_vala_map (ValaGtkModule* self, ValaNamespace* ns) {
	g_return_if_fail (self != NULL);
	g_return_if_fail (ns != NULL);
	{
		ValaNamespace* _tmp0_;
		ValaList* _tmp1_ = NULL;
		ValaList* _cl_list;
		ValaList* _tmp2_;
		gint _tmp3_;
		gint _tmp4_;
		gint _cl_size;
		gint _cl_index;
		_tmp0_ = ns;
		_tmp1_ = vala_namespace_get_classes (_tmp0_);
		_cl_list = _tmp1_;
		_tmp2_ = _cl_list;
		_tmp3_ = vala_collection_get_size ((ValaCollection*) _tmp2_);
		_tmp4_ = _tmp3_;
		_cl_size = _tmp4_;
		_cl_index = -1;
		while (TRUE) {
			gint _tmp5_;
			gint _tmp6_;
			gint _tmp7_;
			ValaList* _tmp8_;
			gint _tmp9_;
			gpointer _tmp10_ = NULL;
			ValaClass* cl;
			ValaClass* _tmp11_;
			gboolean _tmp12_;
			gboolean _tmp13_;
			_tmp5_ = _cl_index;
			_cl_index = _tmp5_ + 1;
			_tmp6_ = _cl_index;
			_tmp7_ = _cl_size;
			if (!(_tmp6_ < _tmp7_)) {
				break;
			}
			_tmp8_ = _cl_list;
			_tmp9_ = _cl_index;
			_tmp10_ = vala_list_get (_tmp8_, _tmp9_);
			cl = (ValaClass*) _tmp10_;
			_tmp11_ = cl;
			_tmp12_ = vala_class_get_is_compact (_tmp11_);
			_tmp13_ = _tmp12_;
			if (!_tmp13_) {
				ValaHashMap* _tmp14_;
				ValaClass* _tmp15_;
				gchar* _tmp16_ = NULL;
				gchar* _tmp17_;
				ValaClass* _tmp18_;
				_tmp14_ = self->priv->cclass_to_vala_map;
				_tmp15_ = cl;
				_tmp16_ = vala_ccode_base_module_get_ccode_name ((ValaCodeNode*) _tmp15_);
				_tmp17_ = _tmp16_;
				_tmp18_ = cl;
				vala_map_set ((ValaMap*) _tmp14_, _tmp17_, _tmp18_);
				_g_free0 (_tmp17_);
			}
			_vala_code_node_unref0 (cl);
		}
		_vala_iterable_unref0 (_cl_list);
	}
	{
		ValaNamespace* _tmp19_;
		ValaList* _tmp20_ = NULL;
		ValaList* _inner_list;
		ValaList* _tmp21_;
		gint _tmp22_;
		gint _tmp23_;
		gint _inner_size;
		gint _inner_index;
		_tmp19_ = ns;
		_tmp20_ = vala_namespace_get_namespaces (_tmp19_);
		_inner_list = _tmp20_;
		_tmp21_ = _inner_list;
		_tmp22_ = vala_collection_get_size ((ValaCollection*) _tmp21_);
		_tmp23_ = _tmp22_;
		_inner_size = _tmp23_;
		_inner_index = -1;
		while (TRUE) {
			gint _tmp24_;
			gint _tmp25_;
			gint _tmp26_;
			ValaList* _tmp27_;
			gint _tmp28_;
			gpointer _tmp29_ = NULL;
			ValaNamespace* inner;
			ValaNamespace* _tmp30_;
			_tmp24_ = _inner_index;
			_inner_index = _tmp24_ + 1;
			_tmp25_ = _inner_index;
			_tmp26_ = _inner_size;
			if (!(_tmp25_ < _tmp26_)) {
				break;
			}
			_tmp27_ = _inner_list;
			_tmp28_ = _inner_index;
			_tmp29_ = vala_list_get (_tmp27_, _tmp28_);
			inner = (ValaNamespace*) _tmp29_;
			_tmp30_ = inner;
			vala_gtk_module_recurse_cclass_to_vala_map (self, _tmp30_);
			_vala_code_node_unref0 (inner);
		}
		_vala_iterable_unref0 (_inner_list);
	}
}


static void vala_gtk_module_ensure_gresource_to_file_map (ValaGtkModule* self) {
	ValaHashMap* _tmp0_;
	GHashFunc _tmp1_;
	GEqualFunc _tmp2_;
	GEqualFunc _tmp3_;
	ValaHashMap* _tmp4_;
	ValaCodeContext* _tmp5_;
	ValaCodeContext* _tmp6_;
	gchar** _tmp7_;
	gint _tmp7__length1;
	g_return_if_fail (self != NULL);
	_tmp0_ = self->priv->gresource_to_file_map;
	if (_tmp0_ != NULL) {
		return;
	}
	_tmp1_ = g_str_hash;
	_tmp2_ = g_str_equal;
	_tmp3_ = g_direct_equal;
	_tmp4_ = vala_hash_map_new (G_TYPE_STRING, (GBoxedCopyFunc) g_strdup, g_free, G_TYPE_STRING, (GBoxedCopyFunc) g_strdup, g_free, _tmp1_, _tmp2_, _tmp3_);
	_vala_map_unref0 (self->priv->gresource_to_file_map);
	self->priv->gresource_to_file_map = _tmp4_;
	_tmp5_ = vala_ccode_base_module_get_context ((ValaCCodeBaseModule*) self);
	_tmp6_ = _tmp5_;
	_tmp7_ = _tmp6_->gresources;
	_tmp7__length1 = _tmp6_->gresources_length1;
	{
		gchar** gresource_collection = NULL;
		gint gresource_collection_length1 = 0;
		gint _gresource_collection_size_ = 0;
		gint gresource_it = 0;
		gresource_collection = _tmp7_;
		gresource_collection_length1 = _tmp7__length1;
		for (gresource_it = 0; gresource_it < _tmp7__length1; gresource_it = gresource_it + 1) {
			gchar* _tmp8_;
			gchar* gresource = NULL;
			_tmp8_ = g_strdup (gresource_collection[gresource_it]);
			gresource = _tmp8_;
			{
				const gchar* _tmp9_;
				gboolean _tmp10_ = FALSE;
				const gchar* _tmp14_;
				gchar* _tmp15_ = NULL;
				gchar* gresource_dir;
				const gchar* _tmp16_;
				ValaMarkupReader* _tmp17_;
				ValaMarkupReader* reader;
				gint state;
				gchar* prefix;
				ValaMarkupReader* _tmp18_;
				ValaMarkupTokenType _tmp19_ = 0;
				ValaMarkupTokenType current_token;
				_tmp9_ = gresource;
				_tmp10_ = g_file_test (_tmp9_, G_FILE_TEST_EXISTS);
				if (!_tmp10_) {
					const gchar* _tmp11_;
					gchar* _tmp12_ = NULL;
					gchar* _tmp13_;
					_tmp11_ = gresource;
					_tmp12_ = g_strdup_printf ("GResources file `%s' does not exist", _tmp11_);
					_tmp13_ = _tmp12_;
					vala_report_error (NULL, _tmp13_);
					_g_free0 (_tmp13_);
					_g_free0 (gresource);
					continue;
				}
				_tmp14_ = gresource;
				_tmp15_ = g_path_get_dirname (_tmp14_);
				gresource_dir = _tmp15_;
				_tmp16_ = gresource;
				_tmp17_ = vala_markup_reader_new (_tmp16_);
				reader = _tmp17_;
				state = 0;
				prefix = NULL;
				_tmp18_ = reader;
				_tmp19_ = vala_markup_reader_read_token (_tmp18_, NULL, NULL);
				current_token = _tmp19_;
				while (TRUE) {
					ValaMarkupTokenType _tmp20_;
					gboolean _tmp21_ = FALSE;
					ValaMarkupTokenType _tmp22_;
					gboolean _tmp26_;
					ValaMarkupReader* _tmp52_;
					ValaMarkupTokenType _tmp53_ = 0;
					_tmp20_ = current_token;
					if (!(_tmp20_ != VALA_MARKUP_TOKEN_TYPE_EOF)) {
						break;
					}
					_tmp22_ = current_token;
					if (_tmp22_ == VALA_MARKUP_TOKEN_TYPE_START_ELEMENT) {
						ValaMarkupReader* _tmp23_;
						const gchar* _tmp24_;
						const gchar* _tmp25_;
						_tmp23_ = reader;
						_tmp24_ = vala_markup_reader_get_name (_tmp23_);
						_tmp25_ = _tmp24_;
						_tmp21_ = g_strcmp0 (_tmp25_, "gresource") == 0;
					} else {
						_tmp21_ = FALSE;
					}
					_tmp26_ = _tmp21_;
					if (_tmp26_) {
						ValaMarkupReader* _tmp27_;
						gchar* _tmp28_ = NULL;
						_tmp27_ = reader;
						_tmp28_ = vala_markup_reader_get_attribute (_tmp27_, "prefix");
						_g_free0 (prefix);
						prefix = _tmp28_;
					} else {
						gboolean _tmp29_ = FALSE;
						ValaMarkupTokenType _tmp30_;
						gboolean _tmp34_;
						_tmp30_ = current_token;
						if (_tmp30_ == VALA_MARKUP_TOKEN_TYPE_START_ELEMENT) {
							ValaMarkupReader* _tmp31_;
							const gchar* _tmp32_;
							const gchar* _tmp33_;
							_tmp31_ = reader;
							_tmp32_ = vala_markup_reader_get_name (_tmp31_);
							_tmp33_ = _tmp32_;
							_tmp29_ = g_strcmp0 (_tmp33_, "file") == 0;
						} else {
							_tmp29_ = FALSE;
						}
						_tmp34_ = _tmp29_;
						if (_tmp34_) {
							state = 1;
						} else {
							gboolean _tmp35_ = FALSE;
							gint _tmp36_;
							gboolean _tmp38_;
							_tmp36_ = state;
							if (_tmp36_ == 1) {
								ValaMarkupTokenType _tmp37_;
								_tmp37_ = current_token;
								_tmp35_ = _tmp37_ == VALA_MARKUP_TOKEN_TYPE_TEXT;
							} else {
								_tmp35_ = FALSE;
							}
							_tmp38_ = _tmp35_;
							if (_tmp38_) {
								ValaMarkupReader* _tmp39_;
								const gchar* _tmp40_;
								const gchar* _tmp41_;
								gchar* _tmp42_;
								gchar* name;
								ValaHashMap* _tmp43_;
								const gchar* _tmp44_;
								const gchar* _tmp45_;
								gchar* _tmp46_ = NULL;
								gchar* _tmp47_;
								const gchar* _tmp48_;
								const gchar* _tmp49_;
								gchar* _tmp50_ = NULL;
								gchar* _tmp51_;
								_tmp39_ = reader;
								_tmp40_ = vala_markup_reader_get_content (_tmp39_);
								_tmp41_ = _tmp40_;
								_tmp42_ = g_strdup (_tmp41_);
								name = _tmp42_;
								_tmp43_ = self->priv->gresource_to_file_map;
								_tmp44_ = prefix;
								_tmp45_ = name;
								_tmp46_ = g_build_filename (_tmp44_, _tmp45_, NULL);
								_tmp47_ = _tmp46_;
								_tmp48_ = gresource_dir;
								_tmp49_ = name;
								_tmp50_ = g_build_filename (_tmp48_, _tmp49_, NULL);
								_tmp51_ = _tmp50_;
								vala_map_set ((ValaMap*) _tmp43_, _tmp47_, _tmp51_);
								_g_free0 (_tmp51_);
								_g_free0 (_tmp47_);
								state = 0;
								_g_free0 (name);
							}
						}
					}
					_tmp52_ = reader;
					_tmp53_ = vala_markup_reader_read_token (_tmp52_, NULL, NULL);
					current_token = _tmp53_;
				}
				_g_free0 (prefix);
				_g_object_unref0 (reader);
				_g_free0 (gresource_dir);
				_g_free0 (gresource);
			}
		}
	}
}


static gchar* string_replace (const gchar* self, const gchar* old, const gchar* replacement) {
	gchar* result = NULL;
	GError * _inner_error_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	g_return_val_if_fail (old != NULL, NULL);
	g_return_val_if_fail (replacement != NULL, NULL);
	{
		const gchar* _tmp0_;
		gchar* _tmp1_ = NULL;
		gchar* _tmp2_;
		GRegex* _tmp3_;
		GRegex* _tmp4_;
		GRegex* regex;
		GRegex* _tmp5_;
		const gchar* _tmp6_;
		gchar* _tmp7_ = NULL;
		gchar* _tmp8_;
		_tmp0_ = old;
		_tmp1_ = g_regex_escape_string (_tmp0_, -1);
		_tmp2_ = _tmp1_;
		_tmp3_ = g_regex_new (_tmp2_, 0, 0, &_inner_error_);
		_tmp4_ = _tmp3_;
		_g_free0 (_tmp2_);
		regex = _tmp4_;
		if (_inner_error_ != NULL) {
			if (_inner_error_->domain == G_REGEX_ERROR) {
				goto __catch6_g_regex_error;
			}
			g_critical ("file %s: line %d: unexpected error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
			g_clear_error (&_inner_error_);
			return NULL;
		}
		_tmp5_ = regex;
		_tmp6_ = replacement;
		_tmp7_ = g_regex_replace_literal (_tmp5_, self, (gssize) (-1), 0, _tmp6_, 0, &_inner_error_);
		_tmp8_ = _tmp7_;
		if (_inner_error_ != NULL) {
			_g_regex_unref0 (regex);
			if (_inner_error_->domain == G_REGEX_ERROR) {
				goto __catch6_g_regex_error;
			}
			_g_regex_unref0 (regex);
			g_critical ("file %s: line %d: unexpected error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
			g_clear_error (&_inner_error_);
			return NULL;
		}
		result = _tmp8_;
		_g_regex_unref0 (regex);
		return result;
	}
	goto __finally6;
	__catch6_g_regex_error:
	{
		GError* e = NULL;
		e = _inner_error_;
		_inner_error_ = NULL;
		g_assert_not_reached ();
		_g_error_free0 (e);
	}
	__finally6:
	if (_inner_error_ != NULL) {
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return NULL;
	}
}


static void vala_gtk_module_process_current_ui_resource (ValaGtkModule* self, const gchar* ui_resource, ValaCodeNode* node) {
	ValaHashMap* _tmp0_;
	const gchar* _tmp1_;
	gpointer _tmp2_ = NULL;
	gchar* ui_file;
	gboolean _tmp3_ = FALSE;
	const gchar* _tmp4_;
	gboolean _tmp7_;
	GHashFunc _tmp15_;
	GEqualFunc _tmp16_;
	GEqualFunc _tmp17_;
	ValaHashMap* _tmp18_;
	GHashFunc _tmp19_;
	GEqualFunc _tmp20_;
	GEqualFunc _tmp21_;
	ValaHashMap* _tmp22_;
	const gchar* _tmp23_;
	ValaMarkupReader* _tmp24_;
	ValaMarkupReader* reader;
	ValaClass* current_class;
	gboolean template_tag_found;
	ValaMarkupReader* _tmp25_;
	ValaMarkupTokenType _tmp26_ = 0;
	ValaMarkupTokenType current_token;
	gboolean _tmp81_;
	g_return_if_fail (self != NULL);
	g_return_if_fail (ui_resource != NULL);
	g_return_if_fail (node != NULL);
	vala_gtk_module_ensure_cclass_to_vala_map (self);
	vala_gtk_module_ensure_gresource_to_file_map (self);
	_vala_map_unref0 (self->priv->current_handler_to_signal_map);
	self->priv->current_handler_to_signal_map = NULL;
	_vala_map_unref0 (self->priv->current_child_to_class_map);
	self->priv->current_child_to_class_map = NULL;
	_tmp0_ = self->priv->gresource_to_file_map;
	_tmp1_ = ui_resource;
	_tmp2_ = vala_map_get ((ValaMap*) _tmp0_, _tmp1_);
	ui_file = (gchar*) _tmp2_;
	_tmp4_ = ui_file;
	if (_tmp4_ == NULL) {
		_tmp3_ = TRUE;
	} else {
		const gchar* _tmp5_;
		gboolean _tmp6_ = FALSE;
		_tmp5_ = ui_file;
		_tmp6_ = g_file_test (_tmp5_, G_FILE_TEST_EXISTS);
		_tmp3_ = !_tmp6_;
	}
	_tmp7_ = _tmp3_;
	if (_tmp7_) {
		ValaCodeNode* _tmp8_;
		ValaCodeNode* _tmp9_;
		ValaSourceReference* _tmp10_;
		ValaSourceReference* _tmp11_;
		const gchar* _tmp12_;
		gchar* _tmp13_ = NULL;
		gchar* _tmp14_;
		_tmp8_ = node;
		vala_code_node_set_error (_tmp8_, TRUE);
		_tmp9_ = node;
		_tmp10_ = vala_code_node_get_source_reference (_tmp9_);
		_tmp11_ = _tmp10_;
		_tmp12_ = ui_resource;
		_tmp13_ = g_strdup_printf ("UI resource not found: `%s'. Please make sure to specify the proper GR" \
"esources xml files with --gresources.", _tmp12_);
		_tmp14_ = _tmp13_;
		vala_report_error (_tmp11_, _tmp14_);
		_g_free0 (_tmp14_);
		_g_free0 (ui_file);
		return;
	}
	_tmp15_ = g_str_hash;
	_tmp16_ = g_str_equal;
	_tmp17_ = g_direct_equal;
	_tmp18_ = vala_hash_map_new (G_TYPE_STRING, (GBoxedCopyFunc) g_strdup, g_free, VALA_TYPE_SIGNAL, (GBoxedCopyFunc) vala_code_node_ref, vala_code_node_unref, _tmp15_, _tmp16_, _tmp17_);
	_vala_map_unref0 (self->priv->current_handler_to_signal_map);
	self->priv->current_handler_to_signal_map = _tmp18_;
	_tmp19_ = g_str_hash;
	_tmp20_ = g_str_equal;
	_tmp21_ = g_direct_equal;
	_tmp22_ = vala_hash_map_new (G_TYPE_STRING, (GBoxedCopyFunc) g_strdup, g_free, VALA_TYPE_CLASS, (GBoxedCopyFunc) vala_code_node_ref, vala_code_node_unref, _tmp19_, _tmp20_, _tmp21_);
	_vala_map_unref0 (self->priv->current_child_to_class_map);
	self->priv->current_child_to_class_map = _tmp22_;
	_tmp23_ = ui_file;
	_tmp24_ = vala_markup_reader_new (_tmp23_);
	reader = _tmp24_;
	current_class = NULL;
	template_tag_found = FALSE;
	_tmp25_ = reader;
	_tmp26_ = vala_markup_reader_read_token (_tmp25_, NULL, NULL);
	current_token = _tmp26_;
	while (TRUE) {
		ValaMarkupTokenType _tmp27_;
		gboolean _tmp28_ = FALSE;
		ValaMarkupTokenType _tmp29_;
		gboolean _tmp38_;
		ValaMarkupReader* _tmp79_;
		ValaMarkupTokenType _tmp80_ = 0;
		_tmp27_ = current_token;
		if (!(_tmp27_ != VALA_MARKUP_TOKEN_TYPE_EOF)) {
			break;
		}
		_tmp29_ = current_token;
		if (_tmp29_ == VALA_MARKUP_TOKEN_TYPE_START_ELEMENT) {
			gboolean _tmp30_ = FALSE;
			ValaMarkupReader* _tmp31_;
			const gchar* _tmp32_;
			const gchar* _tmp33_;
			gboolean _tmp37_;
			_tmp31_ = reader;
			_tmp32_ = vala_markup_reader_get_name (_tmp31_);
			_tmp33_ = _tmp32_;
			if (g_strcmp0 (_tmp33_, "template") == 0) {
				_tmp30_ = TRUE;
			} else {
				ValaMarkupReader* _tmp34_;
				const gchar* _tmp35_;
				const gchar* _tmp36_;
				_tmp34_ = reader;
				_tmp35_ = vala_markup_reader_get_name (_tmp34_);
				_tmp36_ = _tmp35_;
				_tmp30_ = g_strcmp0 (_tmp36_, "object") == 0;
			}
			_tmp37_ = _tmp30_;
			_tmp28_ = _tmp37_;
		} else {
			_tmp28_ = FALSE;
		}
		_tmp38_ = _tmp28_;
		if (_tmp38_) {
			ValaMarkupReader* _tmp39_;
			const gchar* _tmp40_;
			const gchar* _tmp41_;
			ValaMarkupReader* _tmp42_;
			gchar* _tmp43_ = NULL;
			gchar* class_name;
			const gchar* _tmp44_;
			_tmp39_ = reader;
			_tmp40_ = vala_markup_reader_get_name (_tmp39_);
			_tmp41_ = _tmp40_;
			if (g_strcmp0 (_tmp41_, "template") == 0) {
				template_tag_found = TRUE;
			}
			_tmp42_ = reader;
			_tmp43_ = vala_markup_reader_get_attribute (_tmp42_, "class");
			class_name = _tmp43_;
			_tmp44_ = class_name;
			if (_tmp44_ != NULL) {
				ValaHashMap* _tmp45_;
				const gchar* _tmp46_;
				gpointer _tmp47_ = NULL;
				ValaMarkupReader* _tmp48_;
				gchar* _tmp49_ = NULL;
				gchar* child_name;
				const gchar* _tmp50_;
				_tmp45_ = self->priv->cclass_to_vala_map;
				_tmp46_ = class_name;
				_tmp47_ = vala_map_get ((ValaMap*) _tmp45_, _tmp46_);
				_vala_code_node_unref0 (current_class);
				current_class = (ValaClass*) _tmp47_;
				_tmp48_ = reader;
				_tmp49_ = vala_markup_reader_get_attribute (_tmp48_, "id");
				child_name = _tmp49_;
				_tmp50_ = child_name;
				if (_tmp50_ != NULL) {
					ValaHashMap* _tmp51_;
					const gchar* _tmp52_;
					ValaClass* _tmp53_;
					_tmp51_ = self->priv->current_child_to_class_map;
					_tmp52_ = child_name;
					_tmp53_ = current_class;
					vala_map_set ((ValaMap*) _tmp51_, _tmp52_, _tmp53_);
				}
				_g_free0 (child_name);
			}
			_g_free0 (class_name);
		} else {
			gboolean _tmp54_ = FALSE;
			gboolean _tmp55_ = FALSE;
			ValaClass* _tmp56_;
			gboolean _tmp58_;
			gboolean _tmp62_;
			_tmp56_ = current_class;
			if (_tmp56_ != NULL) {
				ValaMarkupTokenType _tmp57_;
				_tmp57_ = current_token;
				_tmp55_ = _tmp57_ == VALA_MARKUP_TOKEN_TYPE_START_ELEMENT;
			} else {
				_tmp55_ = FALSE;
			}
			_tmp58_ = _tmp55_;
			if (_tmp58_) {
				ValaMarkupReader* _tmp59_;
				const gchar* _tmp60_;
				const gchar* _tmp61_;
				_tmp59_ = reader;
				_tmp60_ = vala_markup_reader_get_name (_tmp59_);
				_tmp61_ = _tmp60_;
				_tmp54_ = g_strcmp0 (_tmp61_, "signal") == 0;
			} else {
				_tmp54_ = FALSE;
			}
			_tmp62_ = _tmp54_;
			if (_tmp62_) {
				ValaMarkupReader* _tmp63_;
				gchar* _tmp64_ = NULL;
				gchar* signal_name;
				ValaMarkupReader* _tmp65_;
				gchar* _tmp66_ = NULL;
				gchar* handler_name;
				ValaClass* _tmp67_;
				_tmp63_ = reader;
				_tmp64_ = vala_markup_reader_get_attribute (_tmp63_, "name");
				signal_name = _tmp64_;
				_tmp65_ = reader;
				_tmp66_ = vala_markup_reader_get_attribute (_tmp65_, "handler");
				handler_name = _tmp66_;
				_tmp67_ = current_class;
				if (_tmp67_ != NULL) {
					ValaClass* _tmp68_;
					const gchar* _tmp69_;
					gchar* _tmp70_ = NULL;
					gchar* _tmp71_;
					ValaSymbol* _tmp72_ = NULL;
					ValaSignal* _tmp73_;
					ValaSignal* _tmp74_;
					ValaSignal* sig;
					ValaSignal* _tmp75_;
					_tmp68_ = current_class;
					_tmp69_ = signal_name;
					_tmp70_ = string_replace (_tmp69_, "-", "_");
					_tmp71_ = _tmp70_;
					_tmp72_ = vala_semantic_analyzer_symbol_lookup_inherited ((ValaSymbol*) _tmp68_, _tmp71_);
					_tmp73_ = G_TYPE_CHECK_INSTANCE_TYPE (_tmp72_, VALA_TYPE_SIGNAL) ? ((ValaSignal*) _tmp72_) : NULL;
					if (_tmp73_ == NULL) {
						_vala_code_node_unref0 (_tmp72_);
					}
					_tmp74_ = _tmp73_;
					_g_free0 (_tmp71_);
					sig = _tmp74_;
					_tmp75_ = sig;
					if (_tmp75_ != NULL) {
						ValaHashMap* _tmp76_;
						const gchar* _tmp77_;
						ValaSignal* _tmp78_;
						_tmp76_ = self->priv->current_handler_to_signal_map;
						_tmp77_ = handler_name;
						_tmp78_ = sig;
						vala_map_set ((ValaMap*) _tmp76_, _tmp77_, _tmp78_);
					}
					_vala_code_node_unref0 (sig);
				}
				_g_free0 (handler_name);
				_g_free0 (signal_name);
			}
		}
		_tmp79_ = reader;
		_tmp80_ = vala_markup_reader_read_token (_tmp79_, NULL, NULL);
		current_token = _tmp80_;
	}
	_tmp81_ = template_tag_found;
	if (!_tmp81_) {
		ValaCodeNode* _tmp82_;
		ValaSourceReference* _tmp83_;
		ValaSourceReference* _tmp84_;
		const gchar* _tmp85_;
		gchar* _tmp86_ = NULL;
		gchar* _tmp87_;
		_tmp82_ = node;
		_tmp83_ = vala_code_node_get_source_reference (_tmp82_);
		_tmp84_ = _tmp83_;
		_tmp85_ = ui_resource;
		_tmp86_ = g_strdup_printf ("ui resource `%s' does not describe a valid composite template", _tmp85_);
		_tmp87_ = _tmp86_;
		vala_report_error (_tmp84_, _tmp87_);
		_g_free0 (_tmp87_);
	}
	_vala_code_node_unref0 (current_class);
	_g_object_unref0 (reader);
	_g_free0 (ui_file);
}


static gboolean vala_gtk_module_is_gtk_template (ValaGtkModule* self, ValaClass* cl) {
	gboolean result = FALSE;
	ValaClass* _tmp0_;
	ValaAttribute* _tmp1_ = NULL;
	ValaAttribute* attr;
	ValaAttribute* _tmp2_;
	g_return_val_if_fail (self != NULL, FALSE);
	g_return_val_if_fail (cl != NULL, FALSE);
	_tmp0_ = cl;
	_tmp1_ = vala_code_node_get_attribute ((ValaCodeNode*) _tmp0_, "GtkTemplate");
	attr = _tmp1_;
	_tmp2_ = attr;
	if (_tmp2_ != NULL) {
		gboolean _tmp3_ = FALSE;
		ValaClass* _tmp4_;
		gboolean _tmp8_;
		ValaCodeContext* _tmp16_;
		ValaCodeContext* _tmp17_;
		gboolean _tmp18_ = FALSE;
		_tmp4_ = ((ValaCCodeBaseModule*) self)->gtk_widget_type;
		if (_tmp4_ == NULL) {
			_tmp3_ = TRUE;
		} else {
			ValaClass* _tmp5_;
			ValaClass* _tmp6_;
			gboolean _tmp7_ = FALSE;
			_tmp5_ = cl;
			_tmp6_ = ((ValaCCodeBaseModule*) self)->gtk_widget_type;
			_tmp7_ = vala_typesymbol_is_subtype_of ((ValaTypeSymbol*) _tmp5_, (ValaTypeSymbol*) _tmp6_);
			_tmp3_ = !_tmp7_;
		}
		_tmp8_ = _tmp3_;
		if (_tmp8_) {
			ValaClass* _tmp9_;
			gboolean _tmp10_;
			gboolean _tmp11_;
			_tmp9_ = cl;
			_tmp10_ = vala_code_node_get_error ((ValaCodeNode*) _tmp9_);
			_tmp11_ = _tmp10_;
			if (!_tmp11_) {
				ValaAttribute* _tmp12_;
				ValaSourceReference* _tmp13_;
				ValaSourceReference* _tmp14_;
				ValaClass* _tmp15_;
				_tmp12_ = attr;
				_tmp13_ = vala_code_node_get_source_reference ((ValaCodeNode*) _tmp12_);
				_tmp14_ = _tmp13_;
				vala_report_error (_tmp14_, "subclassing Gtk.Widget is required for using Gtk templates");
				_tmp15_ = cl;
				vala_code_node_set_error ((ValaCodeNode*) _tmp15_, TRUE);
			}
			result = FALSE;
			_vala_code_node_unref0 (attr);
			return result;
		}
		_tmp16_ = vala_ccode_base_module_get_context ((ValaCCodeBaseModule*) self);
		_tmp17_ = _tmp16_;
		_tmp18_ = vala_code_context_require_glib_version (_tmp17_, 2, 38);
		if (!_tmp18_) {
			ValaClass* _tmp19_;
			gboolean _tmp20_;
			gboolean _tmp21_;
			_tmp19_ = cl;
			_tmp20_ = vala_code_node_get_error ((ValaCodeNode*) _tmp19_);
			_tmp21_ = _tmp20_;
			if (!_tmp21_) {
				ValaAttribute* _tmp22_;
				ValaSourceReference* _tmp23_;
				ValaSourceReference* _tmp24_;
				ValaClass* _tmp25_;
				_tmp22_ = attr;
				_tmp23_ = vala_code_node_get_source_reference ((ValaCodeNode*) _tmp22_);
				_tmp24_ = _tmp23_;
				vala_report_error (_tmp24_, "glib 2.38 is required for using Gtk templates (with --target-glib=2.38" \
")");
				_tmp25_ = cl;
				vala_code_node_set_error ((ValaCodeNode*) _tmp25_, TRUE);
			}
			result = FALSE;
			_vala_code_node_unref0 (attr);
			return result;
		}
		result = TRUE;
		_vala_code_node_unref0 (attr);
		return result;
	}
	result = FALSE;
	_vala_code_node_unref0 (attr);
	return result;
}


static void vala_gtk_module_real_generate_class_init (ValaGTypeModule* base, ValaClass* cl) {
	ValaGtkModule * self;
	ValaClass* _tmp0_;
	gboolean _tmp1_ = FALSE;
	ValaClass* _tmp2_;
	gboolean _tmp3_;
	gboolean _tmp4_;
	gboolean _tmp7_;
	ValaClass* _tmp8_;
	gboolean _tmp9_;
	gboolean _tmp10_;
	ValaClass* _tmp34_;
	gchar* _tmp35_ = NULL;
	gchar* ui;
	const gchar* _tmp36_;
	const gchar* _tmp41_;
	ValaClass* _tmp42_;
	ValaCCodeIdentifier* _tmp43_;
	ValaCCodeIdentifier* _tmp44_;
	ValaCCodeFunctionCall* _tmp45_;
	ValaCCodeFunctionCall* _tmp46_;
	ValaCCodeFunctionCall* call;
	ValaCCodeFunctionCall* _tmp47_;
	ValaCCodeIdentifier* _tmp48_;
	ValaCCodeIdentifier* _tmp49_;
	ValaCCodeFunctionCall* _tmp50_;
	ValaClass* _tmp51_;
	gchar* _tmp52_ = NULL;
	gchar* _tmp53_;
	gchar* _tmp54_;
	gchar* _tmp55_;
	gchar* _tmp56_;
	gchar* _tmp57_;
	ValaCCodeConstant* _tmp58_;
	ValaCCodeConstant* _tmp59_;
	ValaCCodeFunction* _tmp60_;
	ValaCCodeFunction* _tmp61_;
	ValaCCodeFunctionCall* _tmp62_;
	self = (ValaGtkModule*) base;
	g_return_if_fail (cl != NULL);
	_tmp0_ = cl;
	VALA_GTYPE_MODULE_CLASS (vala_gtk_module_parent_class)->generate_class_init ((ValaGTypeModule*) G_TYPE_CHECK_INSTANCE_CAST (self, VALA_TYPE_GSIGNAL_MODULE, ValaGSignalModule), _tmp0_);
	_tmp2_ = cl;
	_tmp3_ = vala_code_node_get_error ((ValaCodeNode*) _tmp2_);
	_tmp4_ = _tmp3_;
	if (_tmp4_) {
		_tmp1_ = TRUE;
	} else {
		ValaClass* _tmp5_;
		gboolean _tmp6_ = FALSE;
		_tmp5_ = cl;
		_tmp6_ = vala_gtk_module_is_gtk_template (self, _tmp5_);
		_tmp1_ = !_tmp6_;
	}
	_tmp7_ = _tmp1_;
	if (_tmp7_) {
		return;
	}
	_tmp8_ = cl;
	_tmp9_ = vala_class_get_has_private_fields (_tmp8_);
	_tmp10_ = _tmp9_;
	if (_tmp10_) {
		ValaClass* _tmp11_;
		gchar* _tmp12_ = NULL;
		gchar* _tmp13_;
		gchar* _tmp14_ = NULL;
		gchar* _tmp15_;
		gchar* private_offset;
		ValaCCodeFunction* _tmp16_;
		ValaCCodeFunction* _tmp17_;
		const gchar* _tmp18_;
		ValaCCodeVariableDeclarator* _tmp19_;
		ValaCCodeVariableDeclarator* _tmp20_;
		ValaCCodeIdentifier* _tmp21_;
		ValaCCodeIdentifier* _tmp22_;
		ValaCCodeFunctionCall* _tmp23_;
		ValaCCodeFunctionCall* _tmp24_;
		ValaCCodeFunctionCall* cgetprivcall;
		ValaCCodeFunctionCall* _tmp25_;
		ValaCCodeIdentifier* _tmp26_;
		ValaCCodeIdentifier* _tmp27_;
		ValaCCodeFunction* _tmp28_;
		ValaCCodeFunction* _tmp29_;
		const gchar* _tmp30_;
		ValaCCodeIdentifier* _tmp31_;
		ValaCCodeIdentifier* _tmp32_;
		ValaCCodeFunctionCall* _tmp33_;
		_tmp11_ = cl;
		_tmp12_ = vala_ccode_base_module_get_ccode_name ((ValaCodeNode*) _tmp11_);
		_tmp13_ = _tmp12_;
		_tmp14_ = g_strdup_printf ("%s_private_offset", _tmp13_);
		_tmp15_ = _tmp14_;
		_g_free0 (_tmp13_);
		private_offset = _tmp15_;
		_tmp16_ = vala_ccode_base_module_get_ccode ((ValaCCodeBaseModule*) self);
		_tmp17_ = _tmp16_;
		_tmp18_ = private_offset;
		_tmp19_ = vala_ccode_variable_declarator_new (_tmp18_, NULL, NULL);
		_tmp20_ = _tmp19_;
		vala_ccode_function_add_declaration (_tmp17_, "gint", (ValaCCodeDeclarator*) _tmp20_, 0);
		_vala_ccode_node_unref0 (_tmp20_);
		_tmp21_ = vala_ccode_identifier_new ("g_type_class_get_instance_private_offset");
		_tmp22_ = _tmp21_;
		_tmp23_ = vala_ccode_function_call_new ((ValaCCodeExpression*) _tmp22_);
		_tmp24_ = _tmp23_;
		_vala_ccode_node_unref0 (_tmp22_);
		cgetprivcall = _tmp24_;
		_tmp25_ = cgetprivcall;
		_tmp26_ = vala_ccode_identifier_new ("klass");
		_tmp27_ = _tmp26_;
		vala_ccode_function_call_add_argument (_tmp25_, (ValaCCodeExpression*) _tmp27_);
		_vala_ccode_node_unref0 (_tmp27_);
		_tmp28_ = vala_ccode_base_module_get_ccode ((ValaCCodeBaseModule*) self);
		_tmp29_ = _tmp28_;
		_tmp30_ = private_offset;
		_tmp31_ = vala_ccode_identifier_new (_tmp30_);
		_tmp32_ = _tmp31_;
		_tmp33_ = cgetprivcall;
		vala_ccode_function_add_assignment (_tmp29_, (ValaCCodeExpression*) _tmp32_, (ValaCCodeExpression*) _tmp33_);
		_vala_ccode_node_unref0 (_tmp32_);
		_vala_ccode_node_unref0 (cgetprivcall);
		_g_free0 (private_offset);
	}
	_tmp34_ = cl;
	_tmp35_ = vala_code_node_get_attribute_string ((ValaCodeNode*) _tmp34_, "GtkTemplate", "ui", NULL);
	ui = _tmp35_;
	_tmp36_ = ui;
	if (_tmp36_ == NULL) {
		ValaClass* _tmp37_;
		ValaSourceReference* _tmp38_;
		ValaSourceReference* _tmp39_;
		ValaClass* _tmp40_;
		_tmp37_ = cl;
		_tmp38_ = vala_code_node_get_source_reference ((ValaCodeNode*) _tmp37_);
		_tmp39_ = _tmp38_;
		vala_report_error (_tmp39_, "empty ui resource declaration for Gtk widget template");
		_tmp40_ = cl;
		vala_code_node_set_error ((ValaCodeNode*) _tmp40_, TRUE);
		_g_free0 (ui);
		return;
	}
	_tmp41_ = ui;
	_tmp42_ = cl;
	vala_gtk_module_process_current_ui_resource (self, _tmp41_, (ValaCodeNode*) _tmp42_);
	_tmp43_ = vala_ccode_identifier_new ("gtk_widget_class_set_template_from_resource");
	_tmp44_ = _tmp43_;
	_tmp45_ = vala_ccode_function_call_new ((ValaCCodeExpression*) _tmp44_);
	_tmp46_ = _tmp45_;
	_vala_ccode_node_unref0 (_tmp44_);
	call = _tmp46_;
	_tmp47_ = call;
	_tmp48_ = vala_ccode_identifier_new ("GTK_WIDGET_CLASS (klass)");
	_tmp49_ = _tmp48_;
	vala_ccode_function_call_add_argument (_tmp47_, (ValaCCodeExpression*) _tmp49_);
	_vala_ccode_node_unref0 (_tmp49_);
	_tmp50_ = call;
	_tmp51_ = cl;
	_tmp52_ = vala_code_node_get_attribute_string ((ValaCodeNode*) _tmp51_, "GtkTemplate", "ui", NULL);
	_tmp53_ = _tmp52_;
	_tmp54_ = g_strconcat ("\"", _tmp53_, NULL);
	_tmp55_ = _tmp54_;
	_tmp56_ = g_strconcat (_tmp55_, "\"", NULL);
	_tmp57_ = _tmp56_;
	_tmp58_ = vala_ccode_constant_new (_tmp57_);
	_tmp59_ = _tmp58_;
	vala_ccode_function_call_add_argument (_tmp50_, (ValaCCodeExpression*) _tmp59_);
	_vala_ccode_node_unref0 (_tmp59_);
	_g_free0 (_tmp57_);
	_g_free0 (_tmp55_);
	_g_free0 (_tmp53_);
	_tmp60_ = vala_ccode_base_module_get_ccode ((ValaCCodeBaseModule*) self);
	_tmp61_ = _tmp60_;
	_tmp62_ = call;
	vala_ccode_function_add_expression (_tmp61_, (ValaCCodeExpression*) _tmp62_);
	_vala_ccode_node_unref0 (call);
	_g_free0 (ui);
}


static gpointer _vala_code_node_ref0 (gpointer self) {
	return self ? vala_code_node_ref (self) : NULL;
}


static gpointer _vala_ccode_node_ref0 (gpointer self) {
	return self ? vala_ccode_node_ref (self) : NULL;
}


static void vala_gtk_module_real_visit_field (ValaCodeVisitor* base, ValaField* f) {
	ValaGtkModule * self;
	ValaField* _tmp0_;
	ValaClass* _tmp1_;
	ValaClass* _tmp2_;
	ValaClass* _tmp3_;
	ValaClass* cl;
	gboolean _tmp4_ = FALSE;
	ValaClass* _tmp5_;
	gboolean _tmp9_;
	gboolean _tmp10_ = FALSE;
	ValaField* _tmp11_;
	ValaMemberBinding _tmp12_;
	ValaMemberBinding _tmp13_;
	gboolean _tmp17_;
	ValaClass* _tmp18_;
	gboolean _tmp19_ = FALSE;
	ValaCCodeBaseModuleEmitContext* _tmp23_;
	ValaField* _tmp24_;
	ValaField* _tmp25_;
	const gchar* _tmp26_;
	const gchar* _tmp27_;
	gchar* _tmp28_ = NULL;
	gchar* gtk_name;
	ValaHashMap* _tmp29_;
	const gchar* _tmp30_;
	gpointer _tmp31_ = NULL;
	ValaClass* child_class;
	ValaClass* _tmp32_;
	ValaField* _tmp39_;
	ValaDataType* _tmp40_;
	ValaDataType* _tmp41_;
	ValaTypeSymbol* _tmp42_;
	ValaTypeSymbol* _tmp43_;
	ValaClass* _tmp44_;
	ValaClass* field_class;
	gboolean _tmp45_ = FALSE;
	ValaClass* _tmp46_;
	gboolean _tmp50_;
	ValaField* _tmp62_;
	gboolean _tmp63_ = FALSE;
	gboolean internal_child;
	ValaCCodeExpression* offset = NULL;
	ValaField* _tmp64_;
	gboolean _tmp65_ = FALSE;
	ValaCCodeIdentifier* _tmp111_;
	ValaCCodeIdentifier* _tmp112_;
	ValaCCodeFunctionCall* _tmp113_;
	ValaCCodeFunctionCall* _tmp114_;
	ValaCCodeFunctionCall* call;
	ValaCCodeFunctionCall* _tmp115_;
	ValaCCodeIdentifier* _tmp116_;
	ValaCCodeIdentifier* _tmp117_;
	ValaCCodeFunctionCall* _tmp118_;
	const gchar* _tmp119_;
	gchar* _tmp120_ = NULL;
	gchar* _tmp121_;
	ValaCCodeConstant* _tmp122_;
	ValaCCodeConstant* _tmp123_;
	const gchar* _tmp124_ = NULL;
	gboolean _tmp125_;
	ValaCCodeFunctionCall* _tmp126_;
	const gchar* _tmp127_;
	ValaCCodeConstant* _tmp128_;
	ValaCCodeConstant* _tmp129_;
	ValaCCodeFunctionCall* _tmp130_;
	ValaCCodeExpression* _tmp131_;
	ValaCCodeFunction* _tmp132_;
	ValaCCodeFunction* _tmp133_;
	ValaCCodeFunctionCall* _tmp134_;
	self = (ValaGtkModule*) base;
	g_return_if_fail (f != NULL);
	_tmp0_ = f;
	VALA_CODE_VISITOR_CLASS (vala_gtk_module_parent_class)->visit_field ((ValaCodeVisitor*) G_TYPE_CHECK_INSTANCE_CAST (self, VALA_TYPE_GSIGNAL_MODULE, ValaGSignalModule), _tmp0_);
	_tmp1_ = vala_ccode_base_module_get_current_class ((ValaCCodeBaseModule*) self);
	_tmp2_ = _tmp1_;
	_tmp3_ = _vala_code_node_ref0 (_tmp2_);
	cl = _tmp3_;
	_tmp5_ = cl;
	if (_tmp5_ == NULL) {
		_tmp4_ = TRUE;
	} else {
		ValaClass* _tmp6_;
		gboolean _tmp7_;
		gboolean _tmp8_;
		_tmp6_ = cl;
		_tmp7_ = vala_code_node_get_error ((ValaCodeNode*) _tmp6_);
		_tmp8_ = _tmp7_;
		_tmp4_ = _tmp8_;
	}
	_tmp9_ = _tmp4_;
	if (_tmp9_) {
		_vala_code_node_unref0 (cl);
		return;
	}
	_tmp11_ = f;
	_tmp12_ = vala_field_get_binding (_tmp11_);
	_tmp13_ = _tmp12_;
	if (_tmp13_ != VALA_MEMBER_BINDING_INSTANCE) {
		_tmp10_ = TRUE;
	} else {
		ValaField* _tmp14_;
		ValaAttribute* _tmp15_ = NULL;
		ValaAttribute* _tmp16_;
		_tmp14_ = f;
		_tmp15_ = vala_code_node_get_attribute ((ValaCodeNode*) _tmp14_, "GtkChild");
		_tmp16_ = _tmp15_;
		_tmp10_ = _tmp16_ == NULL;
		_vala_code_node_unref0 (_tmp16_);
	}
	_tmp17_ = _tmp10_;
	if (_tmp17_) {
		_vala_code_node_unref0 (cl);
		return;
	}
	_tmp18_ = cl;
	_tmp19_ = vala_gtk_module_is_gtk_template (self, _tmp18_);
	if (!_tmp19_) {
		ValaField* _tmp20_;
		ValaSourceReference* _tmp21_;
		ValaSourceReference* _tmp22_;
		_tmp20_ = f;
		_tmp21_ = vala_code_node_get_source_reference ((ValaCodeNode*) _tmp20_);
		_tmp22_ = _tmp21_;
		vala_report_error (_tmp22_, "[GtkChild] is only allowed in classes with a [GtkTemplate] attribute");
		_vala_code_node_unref0 (cl);
		return;
	}
	_tmp23_ = ((ValaCCodeBaseModule*) self)->class_init_context;
	vala_ccode_base_module_push_context ((ValaCCodeBaseModule*) self, _tmp23_);
	_tmp24_ = f;
	_tmp25_ = f;
	_tmp26_ = vala_symbol_get_name ((ValaSymbol*) _tmp25_);
	_tmp27_ = _tmp26_;
	_tmp28_ = vala_code_node_get_attribute_string ((ValaCodeNode*) _tmp24_, "GtkChild", "name", _tmp27_);
	gtk_name = _tmp28_;
	_tmp29_ = self->priv->current_child_to_class_map;
	_tmp30_ = gtk_name;
	_tmp31_ = vala_map_get ((ValaMap*) _tmp29_, _tmp30_);
	child_class = (ValaClass*) _tmp31_;
	_tmp32_ = child_class;
	if (_tmp32_ == NULL) {
		ValaField* _tmp33_;
		ValaSourceReference* _tmp34_;
		ValaSourceReference* _tmp35_;
		const gchar* _tmp36_;
		gchar* _tmp37_ = NULL;
		gchar* _tmp38_;
		_tmp33_ = f;
		_tmp34_ = vala_code_node_get_source_reference ((ValaCodeNode*) _tmp33_);
		_tmp35_ = _tmp34_;
		_tmp36_ = gtk_name;
		_tmp37_ = g_strdup_printf ("could not find child `%s'", _tmp36_);
		_tmp38_ = _tmp37_;
		vala_report_error (_tmp35_, _tmp38_);
		_g_free0 (_tmp38_);
		_vala_code_node_unref0 (child_class);
		_g_free0 (gtk_name);
		_vala_code_node_unref0 (cl);
		return;
	}
	_tmp39_ = f;
	_tmp40_ = vala_variable_get_variable_type ((ValaVariable*) _tmp39_);
	_tmp41_ = _tmp40_;
	_tmp42_ = vala_data_type_get_data_type (_tmp41_);
	_tmp43_ = _tmp42_;
	_tmp44_ = _vala_code_node_ref0 (G_TYPE_CHECK_INSTANCE_TYPE (_tmp43_, VALA_TYPE_CLASS) ? ((ValaClass*) _tmp43_) : NULL);
	field_class = _tmp44_;
	_tmp46_ = field_class;
	if (_tmp46_ == NULL) {
		_tmp45_ = TRUE;
	} else {
		ValaClass* _tmp47_;
		ValaClass* _tmp48_;
		gboolean _tmp49_ = FALSE;
		_tmp47_ = child_class;
		_tmp48_ = field_class;
		_tmp49_ = vala_typesymbol_is_subtype_of ((ValaTypeSymbol*) _tmp47_, (ValaTypeSymbol*) _tmp48_);
		_tmp45_ = !_tmp49_;
	}
	_tmp50_ = _tmp45_;
	if (_tmp50_) {
		ValaField* _tmp51_;
		ValaSourceReference* _tmp52_;
		ValaSourceReference* _tmp53_;
		ValaClass* _tmp54_;
		gchar* _tmp55_ = NULL;
		gchar* _tmp56_;
		ValaClass* _tmp57_;
		gchar* _tmp58_ = NULL;
		gchar* _tmp59_;
		gchar* _tmp60_ = NULL;
		gchar* _tmp61_;
		_tmp51_ = f;
		_tmp52_ = vala_code_node_get_source_reference ((ValaCodeNode*) _tmp51_);
		_tmp53_ = _tmp52_;
		_tmp54_ = child_class;
		_tmp55_ = vala_symbol_get_full_name ((ValaSymbol*) _tmp54_);
		_tmp56_ = _tmp55_;
		_tmp57_ = field_class;
		_tmp58_ = vala_symbol_get_full_name ((ValaSymbol*) _tmp57_);
		_tmp59_ = _tmp58_;
		_tmp60_ = g_strdup_printf ("cannot convert from Gtk child type `%s' to `%s'", _tmp56_, _tmp59_);
		_tmp61_ = _tmp60_;
		vala_report_error (_tmp53_, _tmp61_);
		_g_free0 (_tmp61_);
		_g_free0 (_tmp59_);
		_g_free0 (_tmp56_);
		_vala_code_node_unref0 (field_class);
		_vala_code_node_unref0 (child_class);
		_g_free0 (gtk_name);
		_vala_code_node_unref0 (cl);
		return;
	}
	_tmp62_ = f;
	_tmp63_ = vala_code_node_get_attribute_bool ((ValaCodeNode*) _tmp62_, "GtkChild", "internal", FALSE);
	internal_child = _tmp63_;
	_tmp64_ = f;
	_tmp65_ = vala_symbol_is_private_symbol ((ValaSymbol*) _tmp64_);
	if (_tmp65_) {
		ValaCCodeIdentifier* _tmp66_;
		ValaCCodeIdentifier* _tmp67_;
		ValaCCodeFunctionCall* _tmp68_;
		ValaCCodeFunctionCall* _tmp69_;
		ValaCCodeFunctionCall* private_field_offset;
		ValaCCodeFunctionCall* _tmp70_;
		ValaClass* _tmp71_;
		gchar* _tmp72_ = NULL;
		gchar* _tmp73_;
		gchar* _tmp74_ = NULL;
		gchar* _tmp75_;
		ValaCCodeIdentifier* _tmp76_;
		ValaCCodeIdentifier* _tmp77_;
		ValaCCodeFunctionCall* _tmp78_;
		ValaField* _tmp79_;
		gchar* _tmp80_ = NULL;
		gchar* _tmp81_;
		ValaCCodeIdentifier* _tmp82_;
		ValaCCodeIdentifier* _tmp83_;
		ValaClass* _tmp84_;
		gchar* _tmp85_ = NULL;
		gchar* _tmp86_;
		gchar* _tmp87_ = NULL;
		gchar* _tmp88_;
		ValaCCodeIdentifier* _tmp89_;
		ValaCCodeIdentifier* _tmp90_;
		ValaCCodeFunctionCall* _tmp91_;
		ValaCCodeBinaryExpression* _tmp92_;
		_tmp66_ = vala_ccode_identifier_new ("G_STRUCT_OFFSET");
		_tmp67_ = _tmp66_;
		_tmp68_ = vala_ccode_function_call_new ((ValaCCodeExpression*) _tmp67_);
		_tmp69_ = _tmp68_;
		_vala_ccode_node_unref0 (_tmp67_);
		private_field_offset = _tmp69_;
		_tmp70_ = private_field_offset;
		_tmp71_ = cl;
		_tmp72_ = vala_ccode_base_module_get_ccode_name ((ValaCodeNode*) _tmp71_);
		_tmp73_ = _tmp72_;
		_tmp74_ = g_strdup_printf ("%sPrivate", _tmp73_);
		_tmp75_ = _tmp74_;
		_tmp76_ = vala_ccode_identifier_new (_tmp75_);
		_tmp77_ = _tmp76_;
		vala_ccode_function_call_add_argument (_tmp70_, (ValaCCodeExpression*) _tmp77_);
		_vala_ccode_node_unref0 (_tmp77_);
		_g_free0 (_tmp75_);
		_g_free0 (_tmp73_);
		_tmp78_ = private_field_offset;
		_tmp79_ = f;
		_tmp80_ = vala_ccode_base_module_get_ccode_name ((ValaCodeNode*) _tmp79_);
		_tmp81_ = _tmp80_;
		_tmp82_ = vala_ccode_identifier_new (_tmp81_);
		_tmp83_ = _tmp82_;
		vala_ccode_function_call_add_argument (_tmp78_, (ValaCCodeExpression*) _tmp83_);
		_vala_ccode_node_unref0 (_tmp83_);
		_g_free0 (_tmp81_);
		_tmp84_ = cl;
		_tmp85_ = vala_ccode_base_module_get_ccode_name ((ValaCodeNode*) _tmp84_);
		_tmp86_ = _tmp85_;
		_tmp87_ = g_strdup_printf ("%s_private_offset", _tmp86_);
		_tmp88_ = _tmp87_;
		_tmp89_ = vala_ccode_identifier_new (_tmp88_);
		_tmp90_ = _tmp89_;
		_tmp91_ = private_field_offset;
		_tmp92_ = vala_ccode_binary_expression_new (VALA_CCODE_BINARY_OPERATOR_PLUS, (ValaCCodeExpression*) _tmp90_, (ValaCCodeExpression*) _tmp91_);
		_vala_ccode_node_unref0 (offset);
		offset = (ValaCCodeExpression*) _tmp92_;
		_vala_ccode_node_unref0 (_tmp90_);
		_g_free0 (_tmp88_);
		_g_free0 (_tmp86_);
		_vala_ccode_node_unref0 (private_field_offset);
	} else {
		ValaCCodeIdentifier* _tmp93_;
		ValaCCodeIdentifier* _tmp94_;
		ValaCCodeFunctionCall* _tmp95_;
		ValaCCodeFunctionCall* _tmp96_;
		ValaCCodeFunctionCall* offset_call;
		ValaCCodeFunctionCall* _tmp97_;
		ValaClass* _tmp98_;
		gchar* _tmp99_ = NULL;
		gchar* _tmp100_;
		ValaCCodeIdentifier* _tmp101_;
		ValaCCodeIdentifier* _tmp102_;
		ValaCCodeFunctionCall* _tmp103_;
		ValaField* _tmp104_;
		gchar* _tmp105_ = NULL;
		gchar* _tmp106_;
		ValaCCodeIdentifier* _tmp107_;
		ValaCCodeIdentifier* _tmp108_;
		ValaCCodeFunctionCall* _tmp109_;
		ValaCCodeExpression* _tmp110_;
		_tmp93_ = vala_ccode_identifier_new ("G_STRUCT_OFFSET");
		_tmp94_ = _tmp93_;
		_tmp95_ = vala_ccode_function_call_new ((ValaCCodeExpression*) _tmp94_);
		_tmp96_ = _tmp95_;
		_vala_ccode_node_unref0 (_tmp94_);
		offset_call = _tmp96_;
		_tmp97_ = offset_call;
		_tmp98_ = cl;
		_tmp99_ = vala_ccode_base_module_get_ccode_name ((ValaCodeNode*) _tmp98_);
		_tmp100_ = _tmp99_;
		_tmp101_ = vala_ccode_identifier_new (_tmp100_);
		_tmp102_ = _tmp101_;
		vala_ccode_function_call_add_argument (_tmp97_, (ValaCCodeExpression*) _tmp102_);
		_vala_ccode_node_unref0 (_tmp102_);
		_g_free0 (_tmp100_);
		_tmp103_ = offset_call;
		_tmp104_ = f;
		_tmp105_ = vala_ccode_base_module_get_ccode_name ((ValaCodeNode*) _tmp104_);
		_tmp106_ = _tmp105_;
		_tmp107_ = vala_ccode_identifier_new (_tmp106_);
		_tmp108_ = _tmp107_;
		vala_ccode_function_call_add_argument (_tmp103_, (ValaCCodeExpression*) _tmp108_);
		_vala_ccode_node_unref0 (_tmp108_);
		_g_free0 (_tmp106_);
		_tmp109_ = offset_call;
		_tmp110_ = _vala_ccode_node_ref0 ((ValaCCodeExpression*) _tmp109_);
		_vala_ccode_node_unref0 (offset);
		offset = _tmp110_;
		_vala_ccode_node_unref0 (offset_call);
	}
	_tmp111_ = vala_ccode_identifier_new ("gtk_widget_class_bind_template_child_full");
	_tmp112_ = _tmp111_;
	_tmp113_ = vala_ccode_function_call_new ((ValaCCodeExpression*) _tmp112_);
	_tmp114_ = _tmp113_;
	_vala_ccode_node_unref0 (_tmp112_);
	call = _tmp114_;
	_tmp115_ = call;
	_tmp116_ = vala_ccode_identifier_new ("GTK_WIDGET_CLASS (klass)");
	_tmp117_ = _tmp116_;
	vala_ccode_function_call_add_argument (_tmp115_, (ValaCCodeExpression*) _tmp117_);
	_vala_ccode_node_unref0 (_tmp117_);
	_tmp118_ = call;
	_tmp119_ = gtk_name;
	_tmp120_ = g_strdup_printf ("\"%s\"", _tmp119_);
	_tmp121_ = _tmp120_;
	_tmp122_ = vala_ccode_constant_new (_tmp121_);
	_tmp123_ = _tmp122_;
	vala_ccode_function_call_add_argument (_tmp118_, (ValaCCodeExpression*) _tmp123_);
	_vala_ccode_node_unref0 (_tmp123_);
	_g_free0 (_tmp121_);
	_tmp125_ = internal_child;
	if (_tmp125_) {
		_tmp124_ = "TRUE";
	} else {
		_tmp124_ = "FALSE";
	}
	_tmp126_ = call;
	_tmp127_ = _tmp124_;
	_tmp128_ = vala_ccode_constant_new (_tmp127_);
	_tmp129_ = _tmp128_;
	vala_ccode_function_call_add_argument (_tmp126_, (ValaCCodeExpression*) _tmp129_);
	_vala_ccode_node_unref0 (_tmp129_);
	_tmp130_ = call;
	_tmp131_ = offset;
	vala_ccode_function_call_add_argument (_tmp130_, _tmp131_);
	_tmp132_ = vala_ccode_base_module_get_ccode ((ValaCCodeBaseModule*) self);
	_tmp133_ = _tmp132_;
	_tmp134_ = call;
	vala_ccode_function_add_expression (_tmp133_, (ValaCCodeExpression*) _tmp134_);
	vala_ccode_base_module_pop_context ((ValaCCodeBaseModule*) self);
	_vala_ccode_node_unref0 (call);
	_vala_ccode_node_unref0 (offset);
	_vala_code_node_unref0 (field_class);
	_vala_code_node_unref0 (child_class);
	_g_free0 (gtk_name);
	_vala_code_node_unref0 (cl);
}


static void vala_gtk_module_real_visit_method (ValaCodeVisitor* base, ValaMethod* m) {
	ValaGtkModule * self;
	ValaMethod* _tmp0_;
	ValaClass* _tmp1_;
	ValaClass* _tmp2_;
	ValaClass* _tmp3_;
	ValaClass* cl;
	gboolean _tmp4_ = FALSE;
	gboolean _tmp5_ = FALSE;
	ValaClass* _tmp6_;
	gboolean _tmp10_;
	gboolean _tmp13_;
	gboolean _tmp14_ = FALSE;
	ValaMethod* _tmp15_;
	ValaMemberBinding _tmp16_;
	ValaMemberBinding _tmp17_;
	gboolean _tmp21_;
	ValaMethod* _tmp22_;
	ValaMethod* _tmp23_;
	const gchar* _tmp24_;
	const gchar* _tmp25_;
	gchar* _tmp26_ = NULL;
	gchar* handler_name;
	ValaHashMap* _tmp27_;
	const gchar* _tmp28_;
	gpointer _tmp29_ = NULL;
	ValaSignal* sig;
	ValaSignal* _tmp30_;
	ValaCCodeBaseModuleEmitContext* _tmp37_;
	ValaSignal* _tmp38_;
	self = (ValaGtkModule*) base;
	g_return_if_fail (m != NULL);
	_tmp0_ = m;
	VALA_CODE_VISITOR_CLASS (vala_gtk_module_parent_class)->visit_method ((ValaCodeVisitor*) G_TYPE_CHECK_INSTANCE_CAST (self, VALA_TYPE_GSIGNAL_MODULE, ValaGSignalModule), _tmp0_);
	_tmp1_ = vala_ccode_base_module_get_current_class ((ValaCCodeBaseModule*) self);
	_tmp2_ = _tmp1_;
	_tmp3_ = _vala_code_node_ref0 (_tmp2_);
	cl = _tmp3_;
	_tmp6_ = cl;
	if (_tmp6_ == NULL) {
		_tmp5_ = TRUE;
	} else {
		ValaClass* _tmp7_;
		gboolean _tmp8_;
		gboolean _tmp9_;
		_tmp7_ = cl;
		_tmp8_ = vala_code_node_get_error ((ValaCodeNode*) _tmp7_);
		_tmp9_ = _tmp8_;
		_tmp5_ = _tmp9_;
	}
	_tmp10_ = _tmp5_;
	if (_tmp10_) {
		_tmp4_ = TRUE;
	} else {
		ValaClass* _tmp11_;
		gboolean _tmp12_ = FALSE;
		_tmp11_ = cl;
		_tmp12_ = vala_gtk_module_is_gtk_template (self, _tmp11_);
		_tmp4_ = !_tmp12_;
	}
	_tmp13_ = _tmp4_;
	if (_tmp13_) {
		_vala_code_node_unref0 (cl);
		return;
	}
	_tmp15_ = m;
	_tmp16_ = vala_method_get_binding (_tmp15_);
	_tmp17_ = _tmp16_;
	if (_tmp17_ != VALA_MEMBER_BINDING_INSTANCE) {
		_tmp14_ = TRUE;
	} else {
		ValaMethod* _tmp18_;
		ValaAttribute* _tmp19_ = NULL;
		ValaAttribute* _tmp20_;
		_tmp18_ = m;
		_tmp19_ = vala_code_node_get_attribute ((ValaCodeNode*) _tmp18_, "GtkCallback");
		_tmp20_ = _tmp19_;
		_tmp14_ = _tmp20_ == NULL;
		_vala_code_node_unref0 (_tmp20_);
	}
	_tmp21_ = _tmp14_;
	if (_tmp21_) {
		_vala_code_node_unref0 (cl);
		return;
	}
	_tmp22_ = m;
	_tmp23_ = m;
	_tmp24_ = vala_symbol_get_name ((ValaSymbol*) _tmp23_);
	_tmp25_ = _tmp24_;
	_tmp26_ = vala_code_node_get_attribute_string ((ValaCodeNode*) _tmp22_, "GtkCallback", "name", _tmp25_);
	handler_name = _tmp26_;
	_tmp27_ = self->priv->current_handler_to_signal_map;
	_tmp28_ = handler_name;
	_tmp29_ = vala_map_get ((ValaMap*) _tmp27_, _tmp28_);
	sig = (ValaSignal*) _tmp29_;
	_tmp30_ = sig;
	if (_tmp30_ == NULL) {
		ValaMethod* _tmp31_;
		ValaSourceReference* _tmp32_;
		ValaSourceReference* _tmp33_;
		const gchar* _tmp34_;
		gchar* _tmp35_ = NULL;
		gchar* _tmp36_;
		_tmp31_ = m;
		_tmp32_ = vala_code_node_get_source_reference ((ValaCodeNode*) _tmp31_);
		_tmp33_ = _tmp32_;
		_tmp34_ = handler_name;
		_tmp35_ = g_strdup_printf ("could not find signal for handler `%s'", _tmp34_);
		_tmp36_ = _tmp35_;
		vala_report_error (_tmp33_, _tmp36_);
		_g_free0 (_tmp36_);
		_vala_code_node_unref0 (sig);
		_g_free0 (handler_name);
		_vala_code_node_unref0 (cl);
		return;
	}
	_tmp37_ = ((ValaCCodeBaseModule*) self)->class_init_context;
	vala_ccode_base_module_push_context ((ValaCCodeBaseModule*) self, _tmp37_);
	_tmp38_ = sig;
	if (_tmp38_ != NULL) {
		ValaSignal* _tmp39_;
		ValaCodeContext* _tmp40_;
		ValaCodeContext* _tmp41_;
		ValaMethod* _tmp42_;
		ValaMethodType* _tmp43_;
		ValaMethodType* method_type;
		ValaSignal* _tmp44_;
		ValaSignalType* _tmp45_;
		ValaSignalType* signal_type;
		ValaSignalType* _tmp46_;
		ValaDelegateType* _tmp47_ = NULL;
		ValaDelegateType* delegate_type;
		ValaMethodType* _tmp48_;
		ValaDelegateType* _tmp49_;
		gboolean _tmp50_ = FALSE;
		_tmp39_ = sig;
		_tmp40_ = vala_ccode_base_module_get_context ((ValaCCodeBaseModule*) self);
		_tmp41_ = _tmp40_;
		vala_code_node_check ((ValaCodeNode*) _tmp39_, _tmp41_);
		_tmp42_ = m;
		_tmp43_ = vala_method_type_new (_tmp42_);
		method_type = _tmp43_;
		_tmp44_ = sig;
		_tmp45_ = vala_signal_type_new (_tmp44_);
		signal_type = _tmp45_;
		_tmp46_ = signal_type;
		_tmp47_ = vala_signal_type_get_handler_type (_tmp46_);
		delegate_type = _tmp47_;
		_tmp48_ = method_type;
		_tmp49_ = delegate_type;
		_tmp50_ = vala_data_type_compatible ((ValaDataType*) _tmp48_, (ValaDataType*) _tmp49_);
		if (!_tmp50_) {
			ValaMethod* _tmp51_;
			ValaSourceReference* _tmp52_;
			ValaSourceReference* _tmp53_;
			ValaMethodType* _tmp54_;
			gchar* _tmp55_ = NULL;
			gchar* _tmp56_;
			ValaDelegateType* _tmp57_;
			gchar* _tmp58_ = NULL;
			gchar* _tmp59_;
			ValaDelegateType* _tmp60_;
			ValaDelegate* _tmp61_;
			ValaDelegate* _tmp62_;
			ValaMethod* _tmp63_;
			const gchar* _tmp64_;
			const gchar* _tmp65_;
			gchar* _tmp66_ = NULL;
			gchar* _tmp67_;
			gchar* _tmp68_ = NULL;
			gchar* _tmp69_;
			_tmp51_ = m;
			_tmp52_ = vala_code_node_get_source_reference ((ValaCodeNode*) _tmp51_);
			_tmp53_ = _tmp52_;
			_tmp54_ = method_type;
			_tmp55_ = vala_code_node_to_string ((ValaCodeNode*) _tmp54_);
			_tmp56_ = _tmp55_;
			_tmp57_ = delegate_type;
			_tmp58_ = vala_code_node_to_string ((ValaCodeNode*) _tmp57_);
			_tmp59_ = _tmp58_;
			_tmp60_ = delegate_type;
			_tmp61_ = vala_delegate_type_get_delegate_symbol (_tmp60_);
			_tmp62_ = _tmp61_;
			_tmp63_ = m;
			_tmp64_ = vala_symbol_get_name ((ValaSymbol*) _tmp63_);
			_tmp65_ = _tmp64_;
			_tmp66_ = vala_delegate_get_prototype_string (_tmp62_, _tmp65_);
			_tmp67_ = _tmp66_;
			_tmp68_ = g_strdup_printf ("method `%s' is incompatible with signal `%s', expected `%s'", _tmp56_, _tmp59_, _tmp67_);
			_tmp69_ = _tmp68_;
			vala_report_error (_tmp53_, _tmp69_);
			_g_free0 (_tmp69_);
			_g_free0 (_tmp67_);
			_g_free0 (_tmp59_);
			_g_free0 (_tmp56_);
		} else {
			ValaMethod* _tmp70_;
			ValaSignalType* _tmp71_;
			ValaDelegateType* _tmp72_ = NULL;
			ValaDelegateType* _tmp73_;
			ValaMethod* _tmp74_;
			gchar* _tmp75_ = NULL;
			gchar* _tmp76_;
			gchar* wrapper;
			ValaCCodeIdentifier* _tmp77_;
			ValaCCodeIdentifier* _tmp78_;
			ValaCCodeFunctionCall* _tmp79_;
			ValaCCodeFunctionCall* _tmp80_;
			ValaCCodeFunctionCall* call;
			ValaCCodeFunctionCall* _tmp81_;
			ValaCCodeIdentifier* _tmp82_;
			ValaCCodeIdentifier* _tmp83_;
			ValaCCodeFunctionCall* _tmp84_;
			const gchar* _tmp85_;
			gchar* _tmp86_ = NULL;
			gchar* _tmp87_;
			ValaCCodeConstant* _tmp88_;
			ValaCCodeConstant* _tmp89_;
			ValaCCodeFunctionCall* _tmp90_;
			const gchar* _tmp91_;
			gchar* _tmp92_ = NULL;
			gchar* _tmp93_;
			ValaCCodeIdentifier* _tmp94_;
			ValaCCodeIdentifier* _tmp95_;
			ValaCCodeFunction* _tmp96_;
			ValaCCodeFunction* _tmp97_;
			ValaCCodeFunctionCall* _tmp98_;
			_tmp70_ = m;
			_tmp71_ = signal_type;
			_tmp72_ = vala_signal_type_get_handler_type (_tmp71_);
			_tmp73_ = _tmp72_;
			_tmp74_ = m;
			_tmp75_ = vala_ccode_delegate_module_generate_delegate_wrapper ((ValaCCodeDelegateModule*) self, _tmp70_, _tmp73_, (ValaCodeNode*) _tmp74_);
			_tmp76_ = _tmp75_;
			_vala_code_node_unref0 (_tmp73_);
			wrapper = _tmp76_;
			_tmp77_ = vala_ccode_identifier_new ("gtk_widget_class_bind_template_callback_full");
			_tmp78_ = _tmp77_;
			_tmp79_ = vala_ccode_function_call_new ((ValaCCodeExpression*) _tmp78_);
			_tmp80_ = _tmp79_;
			_vala_ccode_node_unref0 (_tmp78_);
			call = _tmp80_;
			_tmp81_ = call;
			_tmp82_ = vala_ccode_identifier_new ("GTK_WIDGET_CLASS (klass)");
			_tmp83_ = _tmp82_;
			vala_ccode_function_call_add_argument (_tmp81_, (ValaCCodeExpression*) _tmp83_);
			_vala_ccode_node_unref0 (_tmp83_);
			_tmp84_ = call;
			_tmp85_ = handler_name;
			_tmp86_ = g_strdup_printf ("\"%s\"", _tmp85_);
			_tmp87_ = _tmp86_;
			_tmp88_ = vala_ccode_constant_new (_tmp87_);
			_tmp89_ = _tmp88_;
			vala_ccode_function_call_add_argument (_tmp84_, (ValaCCodeExpression*) _tmp89_);
			_vala_ccode_node_unref0 (_tmp89_);
			_g_free0 (_tmp87_);
			_tmp90_ = call;
			_tmp91_ = wrapper;
			_tmp92_ = g_strdup_printf ("G_CALLBACK(%s)", _tmp91_);
			_tmp93_ = _tmp92_;
			_tmp94_ = vala_ccode_identifier_new (_tmp93_);
			_tmp95_ = _tmp94_;
			vala_ccode_function_call_add_argument (_tmp90_, (ValaCCodeExpression*) _tmp95_);
			_vala_ccode_node_unref0 (_tmp95_);
			_g_free0 (_tmp93_);
			_tmp96_ = vala_ccode_base_module_get_ccode ((ValaCCodeBaseModule*) self);
			_tmp97_ = _tmp96_;
			_tmp98_ = call;
			vala_ccode_function_add_expression (_tmp97_, (ValaCCodeExpression*) _tmp98_);
			_vala_ccode_node_unref0 (call);
			_g_free0 (wrapper);
		}
		_vala_code_node_unref0 (delegate_type);
		_vala_code_node_unref0 (signal_type);
		_vala_code_node_unref0 (method_type);
	}
	vala_ccode_base_module_pop_context ((ValaCCodeBaseModule*) self);
	_vala_code_node_unref0 (sig);
	_g_free0 (handler_name);
	_vala_code_node_unref0 (cl);
}


static void vala_gtk_module_real_generate_instance_init (ValaGTypeModule* base, ValaClass* cl) {
	ValaGtkModule * self;
	gboolean _tmp0_ = FALSE;
	gboolean _tmp1_ = FALSE;
	ValaClass* _tmp2_;
	gboolean _tmp6_;
	gboolean _tmp9_;
	ValaCCodeIdentifier* _tmp10_;
	ValaCCodeIdentifier* _tmp11_;
	ValaCCodeFunctionCall* _tmp12_;
	ValaCCodeFunctionCall* _tmp13_;
	ValaCCodeFunctionCall* call;
	ValaCCodeFunctionCall* _tmp14_;
	ValaCCodeIdentifier* _tmp15_;
	ValaCCodeIdentifier* _tmp16_;
	ValaCCodeFunction* _tmp17_;
	ValaCCodeFunction* _tmp18_;
	ValaCCodeFunctionCall* _tmp19_;
	self = (ValaGtkModule*) base;
	g_return_if_fail (cl != NULL);
	_tmp2_ = cl;
	if (_tmp2_ == NULL) {
		_tmp1_ = TRUE;
	} else {
		ValaClass* _tmp3_;
		gboolean _tmp4_;
		gboolean _tmp5_;
		_tmp3_ = cl;
		_tmp4_ = vala_code_node_get_error ((ValaCodeNode*) _tmp3_);
		_tmp5_ = _tmp4_;
		_tmp1_ = _tmp5_;
	}
	_tmp6_ = _tmp1_;
	if (_tmp6_) {
		_tmp0_ = TRUE;
	} else {
		ValaClass* _tmp7_;
		gboolean _tmp8_ = FALSE;
		_tmp7_ = cl;
		_tmp8_ = vala_gtk_module_is_gtk_template (self, _tmp7_);
		_tmp0_ = !_tmp8_;
	}
	_tmp9_ = _tmp0_;
	if (_tmp9_) {
		return;
	}
	_tmp10_ = vala_ccode_identifier_new ("gtk_widget_init_template");
	_tmp11_ = _tmp10_;
	_tmp12_ = vala_ccode_function_call_new ((ValaCCodeExpression*) _tmp11_);
	_tmp13_ = _tmp12_;
	_vala_ccode_node_unref0 (_tmp11_);
	call = _tmp13_;
	_tmp14_ = call;
	_tmp15_ = vala_ccode_identifier_new ("GTK_WIDGET (self)");
	_tmp16_ = _tmp15_;
	vala_ccode_function_call_add_argument (_tmp14_, (ValaCCodeExpression*) _tmp16_);
	_vala_ccode_node_unref0 (_tmp16_);
	_tmp17_ = vala_ccode_base_module_get_ccode ((ValaCCodeBaseModule*) self);
	_tmp18_ = _tmp17_;
	_tmp19_ = call;
	vala_ccode_function_add_expression (_tmp18_, (ValaCCodeExpression*) _tmp19_);
	_vala_ccode_node_unref0 (call);
}


ValaGtkModule* vala_gtk_module_construct (GType object_type) {
	ValaGtkModule* self = NULL;
	self = (ValaGtkModule*) vala_gsignal_module_construct (object_type);
	return self;
}


ValaGtkModule* vala_gtk_module_new (void) {
	return vala_gtk_module_construct (VALA_TYPE_GTK_MODULE);
}


static void vala_gtk_module_class_init (ValaGtkModuleClass * klass) {
	vala_gtk_module_parent_class = g_type_class_peek_parent (klass);
	VALA_CODE_VISITOR_CLASS (klass)->finalize = vala_gtk_module_finalize;
	g_type_class_add_private (klass, sizeof (ValaGtkModulePrivate));
	VALA_GTYPE_MODULE_CLASS (klass)->generate_class_init = vala_gtk_module_real_generate_class_init;
	VALA_CODE_VISITOR_CLASS (klass)->visit_field = vala_gtk_module_real_visit_field;
	VALA_CODE_VISITOR_CLASS (klass)->visit_method = vala_gtk_module_real_visit_method;
	VALA_GTYPE_MODULE_CLASS (klass)->generate_instance_init = vala_gtk_module_real_generate_instance_init;
}


static void vala_gtk_module_instance_init (ValaGtkModule * self) {
	GHashFunc _tmp0_;
	GEqualFunc _tmp1_;
	GEqualFunc _tmp2_;
	ValaHashMap* _tmp3_;
	GHashFunc _tmp4_;
	GEqualFunc _tmp5_;
	GEqualFunc _tmp6_;
	ValaHashMap* _tmp7_;
	self->priv = VALA_GTK_MODULE_GET_PRIVATE (self);
	self->priv->cclass_to_vala_map = NULL;
	self->priv->gresource_to_file_map = NULL;
	_tmp0_ = g_str_hash;
	_tmp1_ = g_str_equal;
	_tmp2_ = g_direct_equal;
	_tmp3_ = vala_hash_map_new (G_TYPE_STRING, (GBoxedCopyFunc) g_strdup, g_free, VALA_TYPE_SIGNAL, (GBoxedCopyFunc) vala_code_node_ref, vala_code_node_unref, _tmp0_, _tmp1_, _tmp2_);
	self->priv->current_handler_to_signal_map = _tmp3_;
	_tmp4_ = g_str_hash;
	_tmp5_ = g_str_equal;
	_tmp6_ = g_direct_equal;
	_tmp7_ = vala_hash_map_new (G_TYPE_STRING, (GBoxedCopyFunc) g_strdup, g_free, VALA_TYPE_CLASS, (GBoxedCopyFunc) vala_code_node_ref, vala_code_node_unref, _tmp4_, _tmp5_, _tmp6_);
	self->priv->current_child_to_class_map = _tmp7_;
}


static void vala_gtk_module_finalize (ValaCodeVisitor* obj) {
	ValaGtkModule * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, VALA_TYPE_GTK_MODULE, ValaGtkModule);
	_vala_map_unref0 (self->priv->cclass_to_vala_map);
	_vala_map_unref0 (self->priv->gresource_to_file_map);
	_vala_map_unref0 (self->priv->current_handler_to_signal_map);
	_vala_map_unref0 (self->priv->current_child_to_class_map);
	VALA_CODE_VISITOR_CLASS (vala_gtk_module_parent_class)->finalize (obj);
}


GType vala_gtk_module_get_type (void) {
	static volatile gsize vala_gtk_module_type_id__volatile = 0;
	if (g_once_init_enter (&vala_gtk_module_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (ValaGtkModuleClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) vala_gtk_module_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (ValaGtkModule), 0, (GInstanceInitFunc) vala_gtk_module_instance_init, NULL };
		GType vala_gtk_module_type_id;
		vala_gtk_module_type_id = g_type_register_static (VALA_TYPE_GSIGNAL_MODULE, "ValaGtkModule", &g_define_type_info, 0);
		g_once_init_leave (&vala_gtk_module_type_id__volatile, vala_gtk_module_type_id);
	}
	return vala_gtk_module_type_id__volatile;
}



